#!/usr/bin/env bash
# Rebuilds supabase/setup_all.sql (all migrations in order, one paste for the Supabase SQL Editor).
# Run after any change to supabase/migrations:   ./supabase/build_setup_all.sh
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
out="$here/setup_all.sql"
{
  echo "-- GENERATED by supabase/build_setup_all.sh. DO NOT EDIT BY HAND: edit supabase/migrations/*.sql and run the script again."
  echo "-- Paste this whole file into Supabase > SQL Editor > New query > Run. It is safe to run on a brand new project only."
  for f in "$here"/migrations/*.sql; do
    echo
    echo "-- ===================================================================================================="
    echo "-- $(basename "$f")"
    echo "-- ===================================================================================================="
    cat "$f"
  done
} > "$out"
echo "wrote $out"
