-- GENERATED by supabase/build_setup_all.sh. DO NOT EDIT BY HAND: edit supabase/migrations/*.sql and run the script again.
-- Paste this whole file into Supabase > SQL Editor > New query > Run. It is safe to run on a brand new project only.

-- ====================================================================================================
-- 20261004000100_cloud_saves.sql
-- ====================================================================================================
-- Mulligan Hills: cloud saves (DEC-012, DEC-058).
--
-- Rules this schema enforces:
--   * The server NEVER picks a winner between a local and a cloud save. Every write is a compare-and-swap on
--     `version`: the client says which cloud version it last saw. If that is not the current version the server
--     answers "conflict" and changes nothing. The game then asks the player (DEC-058). There is no "latest wins".
--   * Save bytes live in a PRIVATE Storage bucket; this table holds only the pointer and a small summary
--     (day, cash, holes, play time) so the conflict prompt can show both sides without downloading anything.
--   * Clients get read access to their own rows only. All writes go through the service-role functions below,
--     which are called by the `cloud-save` and `account` Edge Functions.
--   * A save never carries the paid unlock (SAVE_MIGRATION.md). Nothing here reads or writes entitlements.

-- ---------------------------------------------------------------------------------------------------------------
-- Storage bucket (private, size capped). 8 MiB default cap; raise it in step with CLOUD_SAVE_MAX_BYTES (Edge secret).
-- ---------------------------------------------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('cloud-saves', 'cloud-saves', false, 8388608)
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit;
-- No policies are created on storage.objects on purpose: with row level security on and no policy, browsers and
-- the game client cannot touch the bucket. Only signed URLs minted by the Edge Function (service role) work.

create table public.cloud_saves (
  user_id       uuid        not null references auth.users (id) on delete cascade,
  slot          smallint    not null check (slot between 0 and 4),
  version       integer     not null default 0 check (version >= 0),   -- 0 = no cloud save in this slot yet
  storage_path  text,
  sha256        text        check (sha256 ~ '^[0-9a-f]{64}$'),
  size_bytes    integer     check (size_bytes between 1 and 33554432),
  summary       jsonb       not null default '{}'::jsonb
                            check (jsonb_typeof(summary) = 'object' and pg_column_size(summary) <= 2048),
  pending_path  text,                                                  -- an upload in flight (at most one per slot)
  pending_at    timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  primary key (user_id, slot),
  check ((version = 0 and storage_path is null)
      or (version > 0 and storage_path is not null and sha256 is not null and size_bytes is not null))
);

comment on table public.cloud_saves is
  'One row per player and save slot. version is bumped on every successful upload. See migration header.';

alter table public.cloud_saves enable row level security;
revoke all on table public.cloud_saves from anon, authenticated;
grant select on table public.cloud_saves to authenticated;   -- anonymous sign-ins also use the authenticated role

create policy cloud_saves_select_own on public.cloud_saves
  for select to authenticated
  using (user_id = (select auth.uid()));
-- No insert/update/delete policy: clients cannot write. (service_role bypasses RLS.)

create or replace function public.mh_touch_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.updated_at := now();
  return new;
end $$;

create trigger cloud_saves_touch before update on public.cloud_saves
  for each row execute function public.mh_touch_updated_at();

-- JSON view of a row, used in every answer so the client always sees the same shape.
create or replace function public.mh_cloud_row_json(r public.cloud_saves) returns jsonb
language sql immutable set search_path = '' as $$
  select jsonb_build_object(
    'slot', r.slot, 'version', r.version, 'sha256', r.sha256, 'size_bytes', r.size_bytes,
    'summary', r.summary, 'updated_at', r.updated_at);
$$;

-- ---------------------------------------------------------------------------------------------------------------
-- begin: reserve an upload. Fails with status 'conflict' unless p_expected equals the current cloud version.
-- ---------------------------------------------------------------------------------------------------------------
create or replace function public.cloud_save_begin(p_user uuid, p_slot int, p_expected int, p_new_path text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  r public.cloud_saves;
  old_pending text;
begin
  if p_slot is null or p_slot not between 0 and 4 then raise exception 'bad_slot'; end if;
  if p_expected is null or p_expected < 0 then raise exception 'bad_expected_version'; end if;
  insert into public.cloud_saves (user_id, slot) values (p_user, p_slot) on conflict do nothing;
  select * into r from public.cloud_saves where user_id = p_user and slot = p_slot for update;
  if r.version <> p_expected then
    return jsonb_build_object('status', 'conflict', 'cloud', public.mh_cloud_row_json(r));
  end if;
  old_pending := r.pending_path;
  update public.cloud_saves set pending_path = p_new_path, pending_at = now()
   where user_id = p_user and slot = p_slot;
  return jsonb_build_object('status', 'ok', 'version', r.version, 'discard_path', old_pending);
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- commit: finish an upload. Same compare-and-swap. The pending path must be the one begin reserved.
-- ---------------------------------------------------------------------------------------------------------------
create or replace function public.cloud_save_commit(
  p_user uuid, p_slot int, p_expected int, p_path text, p_sha256 text, p_size int, p_summary jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  r public.cloud_saves;
  old_path text;
begin
  select * into r from public.cloud_saves where user_id = p_user and slot = p_slot for update;
  if not found then
    return jsonb_build_object('status', 'stale_upload', 'discard_path', p_path);
  end if;
  if r.version <> p_expected then
    return jsonb_build_object('status', 'conflict', 'cloud', public.mh_cloud_row_json(r), 'discard_path', p_path);
  end if;
  if r.pending_path is distinct from p_path then
    return jsonb_build_object('status', 'stale_upload', 'cloud', public.mh_cloud_row_json(r), 'discard_path', p_path);
  end if;
  old_path := r.storage_path;
  update public.cloud_saves
     set version = r.version + 1, storage_path = p_path, sha256 = p_sha256, size_bytes = p_size,
         summary = coalesce(p_summary, '{}'::jsonb), pending_path = null, pending_at = null
   where user_id = p_user and slot = p_slot
   returning * into r;
  return jsonb_build_object('status', 'ok', 'cloud', public.mh_cloud_row_json(r), 'discard_path', old_path);
end $$;

-- list: only slots that hold a save; includes the storage path (service role only) so the function can sign a URL.
create or replace function public.cloud_save_list(p_user uuid) returns jsonb
language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(public.mh_cloud_row_json(c) || jsonb_build_object('storage_path', c.storage_path)
                            order by c.slot), '[]'::jsonb)
    from public.cloud_saves c where c.user_id = p_user and c.version > 0;
$$;

-- delete one slot. Returns the object paths the caller must remove from Storage.
create or replace function public.cloud_save_delete(p_user uuid, p_slot int) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare r public.cloud_saves;
begin
  delete from public.cloud_saves where user_id = p_user and slot = p_slot returning * into r;
  if not found then return jsonb_build_object('status', 'not_found', 'discard_paths', '[]'::jsonb); end if;
  return jsonb_build_object('status', 'ok',
    'discard_paths', to_jsonb(array_remove(array[r.storage_path, r.pending_path], null)));
end $$;

-- every object path a user owns (for account deletion).
create or replace function public.cloud_save_all_paths(p_user uuid) returns jsonb
language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(p), '[]'::jsonb) from (
    select storage_path as p from public.cloud_saves where user_id = p_user and storage_path is not null
    union all
    select pending_path from public.cloud_saves where user_id = p_user and pending_path is not null) t;
$$;

-- import: used by "claim with transfer code". Writes an already-copied object as the next version of a slot.
-- Never overwrites silently: if the slot holds a save and p_overwrite is false the answer is 'conflict'.
create or replace function public.cloud_save_import(
  p_user uuid, p_slot int, p_path text, p_sha256 text, p_size int, p_summary jsonb, p_overwrite boolean)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare r public.cloud_saves; old_path text;
begin
  if p_slot is null or p_slot not between 0 and 4 then raise exception 'bad_slot'; end if;
  insert into public.cloud_saves (user_id, slot) values (p_user, p_slot) on conflict do nothing;
  select * into r from public.cloud_saves where user_id = p_user and slot = p_slot for update;
  if r.version > 0 and not coalesce(p_overwrite, false) then
    return jsonb_build_object('status', 'conflict', 'cloud', public.mh_cloud_row_json(r), 'discard_path', p_path);
  end if;
  old_path := r.storage_path;
  update public.cloud_saves
     set version = r.version + 1, storage_path = p_path, sha256 = p_sha256, size_bytes = p_size,
         summary = coalesce(p_summary, '{}'::jsonb)
   where user_id = p_user and slot = p_slot returning * into r;
  return jsonb_build_object('status', 'ok', 'cloud', public.mh_cloud_row_json(r), 'discard_path', old_path);
end $$;

revoke all on function public.cloud_save_begin(uuid, int, int, text) from public, anon, authenticated;
revoke all on function public.cloud_save_commit(uuid, int, int, text, text, int, jsonb) from public, anon, authenticated;
revoke all on function public.cloud_save_list(uuid) from public, anon, authenticated;
revoke all on function public.cloud_save_delete(uuid, int) from public, anon, authenticated;
revoke all on function public.cloud_save_all_paths(uuid) from public, anon, authenticated;
revoke all on function public.cloud_save_import(uuid, int, text, text, int, jsonb, boolean) from public, anon, authenticated;
grant execute on function public.cloud_save_begin(uuid, int, int, text) to service_role;
grant execute on function public.cloud_save_commit(uuid, int, int, text, text, int, jsonb) to service_role;
grant execute on function public.cloud_save_list(uuid) to service_role;
grant execute on function public.cloud_save_delete(uuid, int) to service_role;
grant execute on function public.cloud_save_all_paths(uuid) to service_role;
grant execute on function public.cloud_save_import(uuid, int, text, text, int, jsonb, boolean) to service_role;

-- ====================================================================================================
-- 20261004000200_transfer_codes.sql
-- ====================================================================================================
-- Mulligan Hills: typed transfer codes (DEC-012) and the web account-deletion path (DEC-031).
--
-- A player with an anonymous account asks the app for a code. The code is 12 characters from a 32 character
-- alphabet (60 bits), valid for 15 minutes, shown once. The database stores only sha256(code), never the code.
-- Typing the code on another device lets THAT device copy the saves across (claim), or lets the owner delete
-- the account from a web page. The code never moves the anonymous identity itself, and it never carries the unlock
-- (the unlock belongs to the Google or Apple account, DEC-030: the new device presses Restore).

create table public.transfer_codes (
  code_hash   text        primary key check (code_hash ~ '^[0-9a-f]{64}$'),
  user_id     uuid        not null references auth.users (id) on delete cascade,
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null,
  used_at     timestamptz
);
create index transfer_codes_user_idx on public.transfer_codes (user_id);

alter table public.transfer_codes enable row level security;
revoke all on table public.transfer_codes from anon, authenticated;
-- no policies: only the service role (Edge Function `account`) touches this table.

-- Create a code. Replaces any older code of the same user. At most one new code per 10 seconds per user.
create or replace function public.transfer_code_create(p_user uuid, p_hash text, p_ttl_seconds int)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare last_created timestamptz;
begin
  if p_ttl_seconds is null or p_ttl_seconds not between 60 and 3600 then raise exception 'bad_ttl'; end if;
  select max(created_at) into last_created from public.transfer_codes where user_id = p_user;
  if last_created is not null and last_created > now() - interval '10 seconds' then
    return jsonb_build_object('status', 'too_fast');
  end if;
  delete from public.transfer_codes where user_id = p_user;
  insert into public.transfer_codes (code_hash, user_id, expires_at)
    values (p_hash, p_user, now() + make_interval(secs => p_ttl_seconds));
  return jsonb_build_object('status', 'ok', 'expires_in', p_ttl_seconds);
end $$;

-- Look a code up without using it (the "who owns these saves" preview).
create or replace function public.transfer_code_peek(p_hash text) returns jsonb
language sql stable security definer set search_path = '' as $$
  select coalesce(
    (select jsonb_build_object('status', 'ok', 'user_id', user_id)
       from public.transfer_codes where code_hash = p_hash and used_at is null and expires_at > now()),
    jsonb_build_object('status', 'invalid'));
$$;

-- Use a code exactly once.
create or replace function public.transfer_code_consume(p_hash text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare uid uuid;
begin
  update public.transfer_codes set used_at = now()
   where code_hash = p_hash and used_at is null and expires_at > now()
   returning user_id into uid;
  if uid is null then return jsonb_build_object('status', 'invalid'); end if;
  return jsonb_build_object('status', 'ok', 'user_id', uid);
end $$;

revoke all on function public.transfer_code_create(uuid, text, int) from public, anon, authenticated;
revoke all on function public.transfer_code_peek(text) from public, anon, authenticated;
revoke all on function public.transfer_code_consume(text) from public, anon, authenticated;
grant execute on function public.transfer_code_create(uuid, text, int) to service_role;
grant execute on function public.transfer_code_peek(text) to service_role;
grant execute on function public.transfer_code_consume(text) to service_role;

-- ====================================================================================================
-- 20261004000300_remote_config.sql
-- ====================================================================================================
-- Mulligan Hills: remote config with kill switches (DEC-044, DEC-059, PROP-03).
--
-- Mirrors docs/spec/data/remote_config.schema.json (schema_version 1). The rules from that schema:
--   * only the listed keys, only values inside the listed ranges (a bad push cannot leave the ranges);
--   * NEVER simulation or rating parameters, NEVER the price (the store owns it);
--   * kill_switches: true = feature ON, false = feature OFF.
-- The database refuses to store a config that breaks the rules, so a typo in the SQL editor cannot reach players.
-- The Edge Function `remote-config` validates again before serving (belt and braces).

create table public.remote_config_versions (
  config_version integer     primary key check (config_version between 1 and 1000000),
  config         jsonb       not null,
  is_active      boolean     not null default false,
  note           text,
  created_at     timestamptz not null default now()
);
create unique index remote_config_one_active on public.remote_config_versions (is_active) where is_active;

-- ---------------------------------------------------------------------------------------------------------------
-- Validation. Returns NULL when the config is fine, otherwise a short message saying what is wrong.
-- ---------------------------------------------------------------------------------------------------------------
create or replace function public.mh__int_in(j jsonb, k text, lo bigint, hi bigint) returns boolean
language sql immutable set search_path = '' as $$
  select jsonb_typeof(j -> k) = 'number'
     and (j ->> k) ~ '^-?[0-9]{1,15}$'
     and (j ->> k)::bigint between lo and hi;
$$;

create or replace function public.mh__keys_ok(j jsonb, required text[], optional text[]) returns boolean
language sql immutable set search_path = '' as $$
  select jsonb_typeof(j) = 'object'
     and not exists (select 1 from jsonb_object_keys(j) k where k <> all (required || optional))
     and not exists (select 1 from unnest(required) r where not (j ? r));
$$;

create or replace function public.mh_validate_remote_config(c jsonb) returns text
language plpgsql immutable set search_path = '' as $$
declare
  ks jsonb; eco jsonb; ev jsonb; k text;
begin
  if jsonb_typeof(c) is distinct from 'object' then return 'config must be an object'; end if;
  if not public.mh__keys_ok(c, array['schema','schema_version','config_version','issued_unix','min_app_version',
                                     'kill_switches','economy','events'], array['banner_key']) then
    return 'top level keys are wrong (unknown key or missing key)';
  end if;
  if c ->> 'schema' is distinct from 'mh.remote_config' then return 'schema must be mh.remote_config'; end if;
  if not public.mh__int_in(c, 'schema_version', 1, 1) then return 'schema_version must be 1'; end if;
  if not public.mh__int_in(c, 'config_version', 1, 1000000) then return 'config_version out of range'; end if;
  if not public.mh__int_in(c, 'issued_unix', 0, 9007199254740991) then return 'issued_unix out of range'; end if;
  if jsonb_typeof(c -> 'min_app_version') is distinct from 'string'
     or (c ->> 'min_app_version') !~ '^[0-9]+\.[0-9]+\.[0-9]+$' then return 'min_app_version must look like 0.1.0'; end if;
  if c ? 'banner_key' and (jsonb_typeof(c -> 'banner_key') is distinct from 'string'
     or (c ->> 'banner_key') !~ '^[a-z][a-z0-9_]*(\.[a-z0-9_]+){1,4}$' or length(c ->> 'banner_key') > 80) then
    return 'banner_key is not a valid string key';
  end if;

  ks := c -> 'kill_switches';
  if not public.mh__keys_ok(ks, array['cloud_sync','daily_challenge','analytics','purchase_flow','tournaments','notifications'],
                            array[]::text[]) then
    return 'kill_switches must hold exactly cloud_sync, daily_challenge, analytics, purchase_flow, tournaments, notifications';
  end if;
  for k in select jsonb_object_keys(ks) loop
    if jsonb_typeof(ks -> k) is distinct from 'boolean' then return 'kill switch ' || k || ' must be true or false'; end if;
  end loop;

  eco := c -> 'economy';
  if not public.mh__keys_ok(eco, array['parcel_base_cost','parcel_growth_pct',
                                       'hole_cost','start_cash','green_fee_min','green_fee_max'], array[]::text[]) then
    return 'economy keys are wrong';
  end if;
  if not public.mh__int_in(eco, 'parcel_base_cost', 1000, 1000000) then return 'parcel_base_cost must be 1000 to 1000000'; end if;
  if not public.mh__int_in(eco, 'parcel_growth_pct', 100, 200) then return 'parcel_growth_pct must be 100 to 200'; end if;
  if not public.mh__int_in(eco, 'hole_cost', 500, 100000) then return 'hole_cost must be 500 to 100000'; end if;
  if not public.mh__int_in(eco, 'start_cash', 1000, 1000000) then return 'start_cash must be 1000 to 1000000'; end if;
  if not public.mh__int_in(eco, 'green_fee_min', 1, 1000) then return 'green_fee_min must be 1 to 1000'; end if;
  if not public.mh__int_in(eco, 'green_fee_max', 1, 10000) then return 'green_fee_max must be 1 to 10000'; end if;
  if (eco ->> 'green_fee_min')::int > (eco ->> 'green_fee_max')::int then return 'green_fee_min is above green_fee_max'; end if;

  ev := c -> 'events';
  if not public.mh__keys_ok(ev, array['random_event_per_day_permille','commission_offer_per_day_permille','event_cash_scale_pct'],
                            array[]::text[]) then return 'events keys are wrong'; end if;
  if not public.mh__int_in(ev, 'random_event_per_day_permille', 0, 500) then return 'random_event_per_day_permille must be 0 to 500'; end if;
  if not public.mh__int_in(ev, 'commission_offer_per_day_permille', 0, 500) then return 'commission_offer_per_day_permille must be 0 to 500'; end if;
  if not public.mh__int_in(ev, 'event_cash_scale_pct', 25, 400) then return 'event_cash_scale_pct must be 25 to 400'; end if;
  return null;
end $$;

create or replace function public.mh__remote_config_guard() returns trigger
language plpgsql set search_path = '' as $$
declare msg text;
begin
  msg := public.mh_validate_remote_config(new.config);
  if msg is not null then raise exception 'invalid remote config: %', msg using errcode = '22023'; end if;
  if (new.config ->> 'config_version')::int is distinct from new.config_version then
    raise exception 'invalid remote config: config_version inside the JSON must equal the row version' using errcode = '22023';
  end if;
  return new;
end $$;

create trigger remote_config_guard before insert or update of config, config_version on public.remote_config_versions
  for each row execute function public.mh__remote_config_guard();

-- ---------------------------------------------------------------------------------------------------------------
-- Row level security: anyone with the app key may READ the active config. Nobody may write from the app.
-- ---------------------------------------------------------------------------------------------------------------
alter table public.remote_config_versions enable row level security;
revoke all on table public.remote_config_versions from anon, authenticated;
grant select on table public.remote_config_versions to anon, authenticated;
create policy remote_config_read_active on public.remote_config_versions
  for select to anon, authenticated using (is_active);

-- ---------------------------------------------------------------------------------------------------------------
-- Admin helpers. Run them in the Supabase SQL Editor (it runs as the owner). The app can never call them.
-- ---------------------------------------------------------------------------------------------------------------

-- Publish a whole new config. config_version and issued_unix are set for you.
create or replace function public.mh_publish_remote_config(p_config jsonb, p_note text default null) returns integer
language plpgsql security definer set search_path = '' as $$
declare nextv integer; cfg jsonb;
begin
  select coalesce(max(config_version), 0) + 1 into nextv from public.remote_config_versions;
  cfg := p_config || jsonb_build_object('config_version', nextv, 'issued_unix', floor(extract(epoch from now()))::bigint);
  update public.remote_config_versions set is_active = false where is_active;
  insert into public.remote_config_versions (config_version, config, is_active, note)
    values (nextv, cfg, true, p_note);
  return nextv;
end $$;

-- Flip one kill switch. true = feature ON, false = feature OFF.
create or replace function public.mh_set_kill_switch(p_name text, p_on boolean, p_note text default null) returns integer
language plpgsql security definer set search_path = '' as $$
declare cur jsonb;
begin
  select config into cur from public.remote_config_versions where is_active;
  if cur is null then raise exception 'no active remote config'; end if;
  if not (cur -> 'kill_switches' ? p_name) then
    raise exception 'unknown kill switch %. Valid: cloud_sync, daily_challenge, analytics, purchase_flow, tournaments, notifications', p_name;
  end if;
  return public.mh_publish_remote_config(
    jsonb_set(cur, array['kill_switches', p_name], to_jsonb(p_on)),
    coalesce(p_note, 'kill switch ' || p_name || ' = ' || p_on::text));
end $$;

-- Go back to the config that was active before the current one (publishes it again as a NEW version number).
create or replace function public.mh_rollback_remote_config() returns integer
language plpgsql security definer set search_path = '' as $$
declare cur integer; prev jsonb;
begin
  select config_version into cur from public.remote_config_versions where is_active;
  select config into prev from public.remote_config_versions where config_version < cur order by config_version desc limit 1;
  if prev is null then raise exception 'there is no earlier config to roll back to'; end if;
  return public.mh_publish_remote_config(prev, 'rollback from version ' || cur);
end $$;

revoke all on function public.mh__int_in(jsonb, text, bigint, bigint) from public, anon, authenticated;
revoke all on function public.mh__keys_ok(jsonb, text[], text[]) from public, anon, authenticated;
revoke all on function public.mh_validate_remote_config(jsonb) from public, anon, authenticated;
revoke all on function public.mh_publish_remote_config(jsonb, text) from public, anon, authenticated;
revoke all on function public.mh_set_kill_switch(text, boolean, text) from public, anon, authenticated;
revoke all on function public.mh_rollback_remote_config() from public, anon, authenticated;
grant execute on function public.mh_validate_remote_config(jsonb) to service_role;
grant execute on function public.mh_publish_remote_config(jsonb, text) to service_role;
grant execute on function public.mh_set_kill_switch(text, boolean, text) to service_role;
grant execute on function public.mh_rollback_remote_config() to service_role;

-- ---------------------------------------------------------------------------------------------------------------
-- First config: the same numbers as docs/spec/data/remote_config.example.json. All six features ON.
-- (analytics being ON here only means the SERVER accepts events; the player still has to opt in, DEC-057.)
-- ---------------------------------------------------------------------------------------------------------------
select public.mh_publish_remote_config(jsonb_build_object(
  'schema', 'mh.remote_config',
  'schema_version', 1,
  'config_version', 1,
  'issued_unix', 0,
  'min_app_version', '0.1.0',
  'kill_switches', jsonb_build_object(
    'cloud_sync', true, 'daily_challenge', true, 'analytics', true,
    'purchase_flow', true, 'tournaments', true, 'notifications', true),
  'economy', jsonb_build_object(
    'parcel_base_cost', 25000, 'parcel_growth_pct', 130,
    'hole_cost', 8000, 'start_cash', 40000, 'green_fee_min', 5, 'green_fee_max', 250),
  'events', jsonb_build_object(
    'random_event_per_day_permille', 60, 'commission_offer_per_day_permille', 40, 'event_cash_scale_pct', 100)
), 'initial config');

-- ====================================================================================================
-- 20261004000400_daily_challenge.sql
-- ====================================================================================================
-- Mulligan Hills: daily challenge leaderboard (DEC-012, DEC-016, DEC-029, DEC-036, DEC-059).
--
-- Trust model (DEC-036): the server does bounds and rate checks only; it does not re-simulate. Scores are claims
-- from the client. The checks here are cheap fences, not proof: score range, only today (or yesterday UTC, for a
-- late submit across midnight), attempt limit per day, minimum gap between submits, engine version format.
-- Names are presets only (DEC-016, DEC-043): the leaderboard shows `name_preset_id`, never free text.
-- The game can switch this off with the remote kill switch `daily_challenge` (the Edge Function checks it).

create table public.daily_scores (
  day                 integer     not null check (day between 0 and 100000),   -- UTC day number: floor(unix / 86400)
  user_id             uuid        not null references auth.users (id) on delete cascade,
  best_score_pm       smallint    not null check (best_score_pm between 0 and 1000),   -- rating engine score_pm, 0..1000
  attempts            smallint    not null default 1 check (attempts between 1 and 10),
  name_preset_id      smallint    not null check (name_preset_id between 0 and 999),
  template_id         text        not null check (template_id ~ '^[a-z][a-z0-9_]{1,39}$'),
  rating_version      text        not null check (rating_version ~ '^MHRATE-[0-9]+\.[0-9]+\.[0-9]+$'),
  sim_version         text        not null check (sim_version ~ '^MHSIM-[0-9]+\.[0-9]+\.[0-9]+$'),
  content_hash        text        check (content_hash ~ '^[0-9a-f]{8,64}$'),
  app_version         text        not null check (app_version ~ '^[0-9]+\.[0-9]+\.[0-9]+$'),
  first_submitted_at  timestamptz not null default now(),
  best_at             timestamptz not null default now(),
  last_submit_at      timestamptz not null default now(),
  primary key (day, user_id)
);
create index daily_scores_rank_idx on public.daily_scores (day, best_score_pm desc, best_at asc);

alter table public.daily_scores enable row level security;
revoke all on table public.daily_scores from anon, authenticated;
-- No policy on purpose: reading goes through daily_leaderboard (no user ids leave the database), writing through
-- daily_submit (service role only).

create or replace function public.mh_utc_day(p_now timestamptz default now()) returns integer
language sql immutable set search_path = '' as $$
  select floor(extract(epoch from p_now) / 86400)::int;
$$;

create or replace function public.daily_submit(
  p_user uuid, p_day int, p_score_pm int, p_name_preset int, p_template text,
  p_rating_version text, p_sim_version text, p_content_hash text, p_app_version text,
  p_max_attempts int default 3, p_min_interval_s int default 5, p_now timestamptz default now())
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  today int := public.mh_utc_day(p_now);
  r public.daily_scores;
  improved boolean := false;
begin
  if p_day is null or p_day not between today - 1 and today then
    return jsonb_build_object('status', 'bad_day', 'today', today);
  end if;
  if p_score_pm is null or p_score_pm not between 0 and 1000 then return jsonb_build_object('status', 'bad_score'); end if;

  select * into r from public.daily_scores where day = p_day and user_id = p_user for update;
  if not found then
    insert into public.daily_scores (day, user_id, best_score_pm, attempts, name_preset_id, template_id, rating_version,
                                     sim_version, content_hash, app_version, first_submitted_at, best_at, last_submit_at)
    values (p_day, p_user, p_score_pm, 1, p_name_preset, p_template, p_rating_version, p_sim_version, p_content_hash,
            p_app_version, p_now, p_now, p_now)
    on conflict (day, user_id) do nothing;
    if found then
      return jsonb_build_object('status', 'ok', 'attempts', 1, 'best_score_pm', p_score_pm, 'improved', true);
    end if;
    select * into r from public.daily_scores where day = p_day and user_id = p_user for update;  -- lost a race
  end if;

  if r.attempts >= p_max_attempts then
    return jsonb_build_object('status', 'attempts_exhausted', 'attempts', r.attempts, 'best_score_pm', r.best_score_pm);
  end if;
  if p_now - r.last_submit_at < make_interval(secs => p_min_interval_s) then
    return jsonb_build_object('status', 'too_fast', 'attempts', r.attempts, 'best_score_pm', r.best_score_pm);
  end if;

  improved := p_score_pm > r.best_score_pm;
  update public.daily_scores set
    attempts = r.attempts + 1,
    last_submit_at = p_now,
    name_preset_id = p_name_preset,
    best_score_pm = case when improved then p_score_pm else r.best_score_pm end,
    best_at = case when improved then p_now else r.best_at end,
    template_id = case when improved then p_template else r.template_id end,
    rating_version = case when improved then p_rating_version else r.rating_version end,
    sim_version = case when improved then p_sim_version else r.sim_version end,
    content_hash = case when improved then p_content_hash else r.content_hash end,
    app_version = case when improved then p_app_version else r.app_version end
  where day = p_day and user_id = p_user
  returning * into r;
  return jsonb_build_object('status', 'ok', 'attempts', r.attempts, 'best_score_pm', r.best_score_pm, 'improved', improved);
end $$;

-- Top N for a day, plus the caller's own rank. Ties: the earlier best score ranks higher.
create or replace function public.daily_leaderboard(p_user uuid, p_day int, p_limit int default 50) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  lim int := least(greatest(coalesce(p_limit, 50), 1), 100);
  result jsonb;
begin
  with ranked as (
    select row_number() over (order by best_score_pm desc, best_at asc, user_id) as rank,
           user_id, name_preset_id, best_score_pm
      from public.daily_scores where day = p_day)
  select jsonb_build_object(
    'day', p_day,
    'total', (select count(*) from ranked),
    'top', coalesce((select jsonb_agg(jsonb_build_object('rank', rank, 'name_preset_id', name_preset_id,
                       'score_pm', best_score_pm, 'is_me', user_id = p_user) order by rank)
                       from ranked where rank <= lim), '[]'::jsonb),
    'me', (select jsonb_build_object('rank', rank, 'name_preset_id', name_preset_id, 'score_pm', best_score_pm)
             from ranked where user_id = p_user))
  into result;
  return result;
end $$;

create or replace function public.daily_purge(p_keep_days int default 30) returns integer
language plpgsql security definer set search_path = '' as $$
declare n integer;
begin
  delete from public.daily_scores where day < public.mh_utc_day() - p_keep_days;
  get diagnostics n = row_count;
  return n;
end $$;

revoke all on function public.mh_utc_day(timestamptz) from public, anon, authenticated;
revoke all on function public.daily_submit(uuid, int, int, int, text, text, text, text, text, int, int, timestamptz) from public, anon, authenticated;
revoke all on function public.daily_leaderboard(uuid, int, int) from public, anon, authenticated;
revoke all on function public.daily_purge(int) from public, anon, authenticated;
grant execute on function public.mh_utc_day(timestamptz) to service_role;
grant execute on function public.daily_submit(uuid, int, int, int, text, text, text, text, text, int, int, timestamptz) to service_role;
grant execute on function public.daily_leaderboard(uuid, int, int) to service_role;
grant execute on function public.daily_purge(int) to service_role;

-- ====================================================================================================
-- 20261004000500_analytics.sql
-- ====================================================================================================
-- Mulligan Hills: analytics events, opt-in only (DEC-057, PROP-04).
--
-- Only the Edge Function `ingest-analytics` writes here, and only events that passed the catalog check
-- (docs/spec/data/analytics_catalog.json). No free text, no advertising id, no hardware id. The only identifiers are
-- a random install_id (the player can reset it in settings) and a random per-launch session_id.
-- Nobody can read this table from the app: row level security is on and there is no policy.
-- Rows are deleted after 180 days (catalog retention_days) and on request (`analytics_delete_install`).

create table public.analytics_events (
  event_id     uuid        primary key,                 -- client generated; makes retries safe (duplicates are ignored)
  name         text        not null check (name ~ '^[a-z][a-z0-9_]{1,39}$'),
  ts_unix      bigint      not null check (ts_unix between 0 and 9007199254740991),
  session_id   uuid        not null,
  install_id   uuid        not null,
  app_version  text        not null check (app_version ~ '^[0-9]+\.[0-9]+\.[0-9]+$'),
  platform     text        not null check (platform in ('android', 'ios')),
  build_kind   text        not null check (build_kind in ('demo', 'full')),
  props        jsonb       not null default '{}'::jsonb
                           check (jsonb_typeof(props) = 'object' and pg_column_size(props) <= 1024),
  received_at  timestamptz not null default now()
);
create index analytics_events_install_idx on public.analytics_events (install_id, received_at);
create index analytics_events_received_idx on public.analytics_events (received_at);
create index analytics_events_name_idx on public.analytics_events (name, received_at);

alter table public.analytics_events enable row level security;
revoke all on table public.analytics_events from anon, authenticated;

-- Insert a batch for ONE install. Throttle: at most p_hourly_cap events per install per rolling hour.
create or replace function public.analytics_ingest(p_install uuid, p_events jsonb, p_hourly_cap int default 600) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  incoming int := jsonb_array_length(p_events);
  recent int;
  inserted int;
begin
  if incoming > 100 then raise exception 'batch_too_large'; end if;
  select count(*) into recent from public.analytics_events
   where install_id = p_install and received_at > now() - interval '1 hour';
  if recent + incoming > p_hourly_cap then
    return jsonb_build_object('status', 'throttled', 'inserted', 0);
  end if;
  insert into public.analytics_events (event_id, name, ts_unix, session_id, install_id, app_version, platform, build_kind, props)
  select e.event_id, e.name, e.ts_unix, e.session_id, p_install, e.app_version, e.platform, e.build_kind, coalesce(e.props, '{}'::jsonb)
    from jsonb_to_recordset(p_events) as e(event_id uuid, name text, ts_unix bigint, session_id uuid, app_version text,
                                           platform text, build_kind text, props jsonb)
  on conflict (event_id) do nothing;
  get diagnostics inserted = row_count;
  return jsonb_build_object('status', 'ok', 'inserted', inserted, 'duplicates', incoming - inserted);
end $$;

create or replace function public.analytics_delete_install(p_install uuid) returns integer
language plpgsql security definer set search_path = '' as $$
declare n integer;
begin
  delete from public.analytics_events where install_id = p_install;
  get diagnostics n = row_count;
  return n;
end $$;

create or replace function public.analytics_purge(p_keep_days int default 180) returns integer
language plpgsql security definer set search_path = '' as $$
declare n integer;
begin
  delete from public.analytics_events where received_at < now() - make_interval(days => p_keep_days);
  get diagnostics n = row_count;
  return n;
end $$;

revoke all on function public.analytics_ingest(uuid, jsonb, int) from public, anon, authenticated;
revoke all on function public.analytics_delete_install(uuid) from public, anon, authenticated;
revoke all on function public.analytics_purge(int) from public, anon, authenticated;
grant execute on function public.analytics_ingest(uuid, jsonb, int) to service_role;
grant execute on function public.analytics_delete_install(uuid) to service_role;
grant execute on function public.analytics_purge(int) to service_role;

-- ====================================================================================================
-- 20261004000600_purchase_verifications.sql
-- ====================================================================================================
-- Mulligan Hills: purchase token reuse counter (closes the "Known gap" in supabase/functions/README.md).
--
-- verify-purchase is anonymous: the unlock belongs to the store receipt, not to a Supabase account (DEC-030).
-- To notice one purchase token being replayed on many devices we keep ONLY a hash of the token, the Google order
-- id, and a counter. A normal player verifies a handful of times (install, reinstall, new phone). The function
-- refuses above a limit (secret PURCHASE_MAX_VERIFICATIONS_30D, default 10).

create table public.purchase_verifications (
  token_hash    text        primary key check (token_hash ~ '^[0-9a-f]{64}$'),   -- sha256 of the purchase token
  product_id    text        not null,
  order_id      text,
  is_test       boolean     not null default false,
  first_seen    timestamptz not null default now(),
  last_seen     timestamptz not null default now(),
  verify_count  integer     not null default 1       -- verifications since window_start
);
alter table public.purchase_verifications enable row level security;
revoke all on table public.purchase_verifications from anon, authenticated;

create or replace function public.purchase_verification_record(
  p_hash text, p_product text, p_order text, p_test boolean, p_window_days int default 30) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare r public.purchase_verifications;
begin
  insert into public.purchase_verifications (token_hash, product_id, order_id, is_test)
    values (p_hash, p_product, nullif(p_order, ''), coalesce(p_test, false))
  on conflict (token_hash) do update set
    verify_count = case when public.purchase_verifications.last_seen < now() - make_interval(days => p_window_days)
                        then 1 else public.purchase_verifications.verify_count + 1 end,
    last_seen = now()
  returning * into r;
  return jsonb_build_object('count', r.verify_count, 'first_seen', r.first_seen);
end $$;

create or replace function public.purchase_verifications_purge(p_keep_days int default 400) returns integer
language plpgsql security definer set search_path = '' as $$
declare n integer;
begin
  delete from public.purchase_verifications where last_seen < now() - make_interval(days => p_keep_days);
  get diagnostics n = row_count;
  return n;
end $$;

revoke all on function public.purchase_verification_record(text, text, text, boolean, int) from public, anon, authenticated;
revoke all on function public.purchase_verifications_purge(int) from public, anon, authenticated;
grant execute on function public.purchase_verification_record(text, text, text, boolean, int) to service_role;
grant execute on function public.purchase_verifications_purge(int) to service_role;

-- ====================================================================================================
-- 20261007000100_purchase_verification_window.sql
-- ====================================================================================================
-- Mulligan Hills: make purchase verification throttling use a fixed window start.
-- The original counter compared against last_seen, which moved on every verification and could therefore
-- keep an actively used purchase token in the same window forever.

alter table public.purchase_verifications
  add column if not exists window_started_at timestamptz;

update public.purchase_verifications
   set window_started_at = first_seen
 where window_started_at is null;

alter table public.purchase_verifications
  alter column window_started_at set default now(),
  alter column window_started_at set not null;

create or replace function public.purchase_verification_record(
  p_hash text, p_product text, p_order text, p_test boolean, p_window_days int default 30) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare r public.purchase_verifications;
begin
  insert into public.purchase_verifications (token_hash, product_id, order_id, is_test, window_started_at)
    values (p_hash, p_product, nullif(p_order, ''), coalesce(p_test, false), now())
  on conflict (token_hash) do update set
    verify_count = case
      when public.purchase_verifications.window_started_at < now() - make_interval(days => p_window_days)
        then 1
      else public.purchase_verifications.verify_count + 1
    end,
    window_started_at = case
      when public.purchase_verifications.window_started_at < now() - make_interval(days => p_window_days)
        then now()
      else public.purchase_verifications.window_started_at
    end,
    last_seen = now()
  returning * into r;
  return jsonb_build_object(
    'count', r.verify_count,
    'first_seen', r.first_seen,
    'window_started_at', r.window_started_at);
end $$;

revoke all on function public.purchase_verification_record(text, text, text, boolean, int) from public, anon, authenticated;
grant execute on function public.purchase_verification_record(text, text, text, boolean, int) to service_role;

-- ====================================================================================================
-- 20261004000700_nightly_cleanup.sql
-- ====================================================================================================
-- Mulligan Hills: one nightly cleanup job. Retention numbers come from docs/spec/data/analytics_catalog.json
-- (analytics 180 days) and docs/spec/data/daily_challenges.json (history_days 30).

create or replace function public.mh_nightly_cleanup() returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  a int; d int; p int; t int;
begin
  a := public.analytics_purge(180);
  d := public.daily_purge(30);
  p := public.purchase_verifications_purge(400);
  delete from public.transfer_codes where expires_at < now() - interval '1 day';
  get diagnostics t = row_count;
  return jsonb_build_object('analytics_deleted', a, 'daily_deleted', d, 'purchase_rows_deleted', p, 'codes_deleted', t);
end $$;

revoke all on function public.mh_nightly_cleanup() from public, anon, authenticated;
grant execute on function public.mh_nightly_cleanup() to service_role;

-- Schedule it with pg_cron when the extension can be enabled. If this block prints a NOTICE instead, enable
-- "pg_cron" in the Supabase dashboard (Database > Extensions) and run the select cron.schedule line from the
-- setup guide by hand. The migration never fails because of this.
do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron;
    perform cron.schedule('mh-nightly-cleanup', '17 3 * * *', 'select public.mh_nightly_cleanup()');
  else
    raise notice 'pg_cron is not available here; schedule public.mh_nightly_cleanup() by hand (see supabase/FOR_NATHAN.md).';
  end if;
exception when others then
  raise notice 'could not schedule cleanup automatically (%). See supabase/FOR_NATHAN.md.', sqlerrm;
end $$;
