extends GdUnitTestSuite
## Golden save fixtures generated by tools/reference/terrain/save_ref.py (6 x 4 cells, uncompressed bodies).
## Cross-checks the GDScript codec against the Python reference byte for byte, and the v1 -> v2 migration.
## NOT YET RUN.

const DIR: String = "res://tests/terrain/golden/"
const PATH: String = "user://mh_test_golden.mhts"


func _read(path: String) -> PackedByteArray:
	var f: FileAccess = FileAccess.open(path, FileAccess.READ)
	assert_object(f).is_not_null()
	var d: PackedByteArray = f.get_buffer(f.get_length())
	f.close()
	return d


func _expected() -> Dictionary:
	var f: FileAccess = FileAccess.open(DIR + "save_golden.json", FileAccess.READ)
	assert_object(f).is_not_null()
	var txt: String = f.get_as_text()
	f.close()
	var parsed: Variant = JSON.parse_string(txt)
	assert_bool(parsed is Dictionary).is_true()
	return parsed


func _grid() -> MHHeightGrid:
	var g := MHHeightGrid.new(6, 4, 1000)
	for i in range(g.sample_count()):
		g.heights[i] = ((i * 7919) % 4001) - 2000
	g.heights[0] = -32768
	g.heights[g.sample_count() - 1] = 32767
	return g


func _v2_splat() -> MHSplatMap:
	var m := MHSplatMap.new(7, 5)
	for t in range(35):
		for l in range(11):
			m.bytes[t * 11 + l] = (t * 7 + l * 13 + 5) & 255
	return m


func _v1_rgba() -> PackedByteArray:
	var b := PackedByteArray()
	b.resize(35 * 4)
	for t in range(35):
		for c in range(4):
			b[t * 4 + c] = (t * 5 + c * 29 + 3) & 255
	return b


func test_v2_fixture_loads_with_expected_hashes_and_data() -> void:
	var ex: Dictionary = _expected()
	var data: PackedByteArray = _read(DIR + "save_v2_6x4.mhts")
	assert_int(data.size()).is_equal(int(ex["v2_file_size"]))
	assert_int(data.decode_u32(16)).is_equal(int(ex["v2_crc"]))
	var r: MHTerrainSave.LoadResult = MHTerrainSave.decode(data)
	assert_int(r.error).is_equal(OK)
	assert_int(r.version).is_equal(2)
	assert_int(r.grid.cells_x).is_equal(6)
	assert_int(r.grid.cells_y).is_equal(4)
	assert_int(r.grid.cell_size_mm).is_equal(1000)
	assert_int(r.grid.hash_fnv1a()).is_equal(int(ex["height_hash"]))
	assert_int(r.splat.hash_fnv1a()).is_equal(int(ex["v2_splat_hash"]))
	assert_bool(r.grid.equals(_grid())).is_true()
	assert_bool(r.splat.bytes == _v2_splat().bytes).is_true()
	assert_int(r.grid.get_h(0, 0)).is_equal(-32768)
	assert_int(r.grid.get_h(6, 4)).is_equal(32767)


func test_encoder_matches_python_v2_fixture_byte_for_byte() -> void:
	var data: PackedByteArray = MHTerrainSave.encode(_grid(), _v2_splat(), false)
	assert_bool(data == _read(DIR + "save_v2_6x4.mhts")).is_true()


func test_legacy_encoder_matches_python_v1_fixture_byte_for_byte() -> void:
	var data: PackedByteArray = MHTerrainSave.encode_legacy_v1(_grid(), _v1_rgba(), false)
	assert_bool(data == _read(DIR + "save_v1_6x4.mhts")).is_true()


func test_v1_fixture_loads_and_maps_four_layers() -> void:
	var ex: Dictionary = _expected()
	var data: PackedByteArray = _read(DIR + "save_v1_6x4.mhts")
	assert_int(data.size()).is_equal(int(ex["v1_file_size"]))
	assert_int(data.decode_u32(16)).is_equal(int(ex["v1_crc"]))
	var r: MHTerrainSave.LoadResult = MHTerrainSave.decode(data)
	assert_int(r.error).is_equal(OK)
	assert_int(r.version).is_equal(1)
	assert_int(r.grid.hash_fnv1a()).is_equal(int(ex["height_hash"]))
	assert_bool(r.grid.equals(_grid())).is_true()
	assert_int(r.splat.samples_x).is_equal(7)
	assert_int(r.splat.samples_y).is_equal(5)
	for t in range(35):
		assert_int(r.splat.bytes[t * 11 + MHSplatMap.Layer.FAIRWAY]).is_equal((t * 5 + 3) & 255)
		assert_int(r.splat.bytes[t * 11 + MHSplatMap.Layer.ROUGH]).is_equal((t * 5 + 29 + 3) & 255)
		assert_int(r.splat.bytes[t * 11 + MHSplatMap.Layer.BUNKER_SAND]).is_equal((t * 5 + 58 + 3) & 255)
		assert_int(r.splat.bytes[t * 11 + MHSplatMap.Layer.GREEN]).is_equal((t * 5 + 87 + 3) & 255)
		for l in [2, 4, 5, 7, 8, 9, 10]:
			assert_int(r.splat.bytes[t * 11 + l]).is_equal(0)


func test_compressed_v1_in_memory_loads_too() -> void:
	var data: PackedByteArray = MHTerrainSave.encode_legacy_v1(_grid(), _v1_rgba(), true)
	var r: MHTerrainSave.LoadResult = MHTerrainSave.decode(data)
	assert_int(r.error).is_equal(OK)
	assert_int(r.version).is_equal(1)
	assert_bool(r.grid.equals(_grid())).is_true()


func test_v1_fixture_migrates_to_v2_and_round_trips_on_disk() -> void:
	var r1: MHTerrainSave.LoadResult = MHTerrainSave.decode(_read(DIR + "save_v1_6x4.mhts"))
	assert_int(MHTerrainSave.save_to_file(PATH, r1.grid, r1.splat)).is_equal(OK)
	var r2: MHTerrainSave.LoadResult = MHTerrainSave.load_from_file(PATH)
	assert_int(r2.error).is_equal(OK)
	assert_int(r2.version).is_equal(2)
	assert_bool(r2.grid.equals(r1.grid)).is_true()
	assert_bool(r2.splat.bytes == r1.splat.bytes).is_true()
	var d: DirAccess = DirAccess.open("user://")
	for p in [PATH, PATH + ".tmp", PATH + ".bak"]:
		if FileAccess.file_exists(p):
			d.remove(p.get_file())


func test_every_byte_flip_in_v1_and_v2_fixtures_is_detected() -> void:
	for fname in ["save_v1_6x4.mhts", "save_v2_6x4.mhts"]:
		var data: PackedByteArray = _read(DIR + fname)
		for i in range(data.size()):
			var bad: PackedByteArray = data.duplicate()
			bad[i] = bad[i] ^ 0x21
			assert_bool(MHTerrainSave.decode(bad).error != OK) \
				.override_failure_message("%s: flip at byte %d not detected" % [fname, i]).is_true()
