extends GdUnitTestSuite
## Golden vectors generated by the Python reference in docs/phase0/forest.md (NOT YET RUN in Godot).


func test_hash32_golden() -> void:
	assert_int(MHForestRng.hash32(0)).is_equal(0)
	assert_int(MHForestRng.hash32(1)).is_equal(1753845952)
	assert_int(MHForestRng.hash32(12345)).is_equal(2435775735)
	assert_int(MHForestRng.hash32(0xFFFFFFFF)).is_equal(1734902346)


func test_rng_sequence_golden() -> void:
	var r: MHForestRng = MHForestRng.new(12345)
	assert_int(r.next_u32()).is_equal(3747499950)
	assert_int(r.next_u32()).is_equal(733492749)
	assert_int(r.next_u32()).is_equal(239011186)


func test_placement_count_and_first_trees() -> void:
	var p: PackedInt32Array = MHTreePlacement.place(12345, 800)
	assert_int(p.size()).is_equal(800 * MHTreePlacement.STRIDE)
	var expected: Array = [299950, 292749, 3586, 134, 1, 10, 100788, 10778, 1772, 129, 1, 1]
	for i in range(expected.size()):
		assert_int(p[i]).is_equal(int(expected[i]))


func test_placement_checksum_golden() -> void:
	assert_int(MHTreePlacement.checksum(MHTreePlacement.place(12345, 800))).is_equal(1635380594)
	assert_int(MHTreePlacement.checksum(MHTreePlacement.place(777, 800))).is_equal(2579281832)


func test_placement_is_repeatable() -> void:
	var a: PackedInt32Array = MHTreePlacement.place(42, 800)
	var b: PackedInt32Array = MHTreePlacement.place(42, 800)
	assert_bool(a == b).is_true()


func test_different_seeds_differ() -> void:
	var a: PackedInt32Array = MHTreePlacement.place(1, 800)
	var b: PackedInt32Array = MHTreePlacement.place(2, 800)
	assert_bool(a == b).is_false()


func test_no_tree_in_exclusion_and_fields_in_range() -> void:
	var p: PackedInt32Array = MHTreePlacement.place(12345, 800)
	var n: int = p.size() / MHTreePlacement.STRIDE
	for i in range(n):
		var o: int = i * MHTreePlacement.STRIDE
		assert_bool(MHTreePlacement.is_excluded(p[o], p[o + 1])).is_false()
		assert_int(p[o]).is_between(0, MHTreePlacement.WORLD_MM - 1)
		assert_int(p[o + 1]).is_between(0, MHTreePlacement.WORLD_MM - 1)
		assert_int(p[o + 2]).is_between(0, 3599)
		assert_int(p[o + 3]).is_between(80, 140)
		assert_int(p[o + 4]).is_between(0, 2)
		assert_int(p[o + 5]).is_between(0, MHTreePlacement.chunk_count() - 1)
		assert_int(p[o + 5]).is_equal(MHTreePlacement.chunk_index_for(p[o], p[o + 1]))


func test_chunk_grouping_covers_all_trees() -> void:
	var p: PackedInt32Array = MHTreePlacement.place(12345, 800)
	var groups: Array = MHTreePlacement.group_by_chunk(p)
	assert_int(groups.size()).is_equal(16)
	var total: int = 0
	for g in groups:
		var pg: PackedInt32Array = g
		total += pg.size()
	assert_int(total).is_equal(800)
	assert_int(MHTreePlacement.chunk_count()).is_between(10, 20)
