class_name MHStrings
extends RefCounted
## English string table and lookup. Every visible UI string comes from here by key (docs/spec/data/LOCALIZATION.md:
## keys are permanent, {name} placeholders, no em dashes). A missing key returns "[key]" and logs once; it never crashes.
## Param convention: a param named "x_key" holds a string KEY; it is translated and also offered as {x}.
## The text below is a DRAFT for Nathan to edit (status draft in the localization workflow). The spec file
## game/data/strings/en.json does not exist yet; moving this table there is a follow-up. The draft files
## game/core/{tournaments,challenges,progression}/*_strings_en.json were merged into this table on 5 Oct 2026
## (achievement names and descriptions, level titles, daily challenge titles, tournament descriptions); the event
## card draft game/core/events/event_cards_strings_en.json is NOT merged yet (no event card screen exists).
## Where a draft and this table disagreed, short names used inside sentences (tournament.<level>.name) and the
## hand-written streak_seven and strategic_par4 texts were kept.

const TABLE: Dictionary = {
	"ach.cat.all": "All",
	"ach.cat.buildings": "Buildings",
	"ach.cat.commissions": "Commissions",
	"ach.cat.daily": "Daily",
	"ach.cat.design": "Design",
	"ach.cat.growth": "Growth",
	"ach.cat.misc": "Other",
	"ach.cat.tournaments": "Tournaments",
	"ach.earned": "Earned, {points} points",
	"ach.hidden": "Hidden achievement",
	"ach.progress": "{have} of {need}, {points} points",
	"ach.summary": "{earned} of {total} earned, {points} points",
	"ach.title": "Achievements",
	"achievement.all_buildings.desc": "Own 10 buildings.",
	"achievement.all_buildings.name": "All Buildings",
	"achievement.balanced_hole.desc": "Build a hole with a rating axis of 70.",
	"achievement.balanced_hole.name": "Balanced Hole",
	"achievement.big_estate.desc": "Own 10 parcels of land.",
	"achievement.big_estate.name": "Big Estate",
	"achievement.busy_day.desc": "Welcome 200 golfers through the course.",
	"achievement.busy_day.name": "Busy Day",
	"achievement.card_collector.desc": "Answer 20 event cards.",
	"achievement.card_collector.name": "Card Collector",
	"achievement.card_player.desc": "Answer an event card.",
	"achievement.card_player.name": "Card Player",
	"achievement.challenge_met.desc": "Meet the daily challenge.",
	"achievement.challenge_met.name": "Challenge Met",
	"achievement.championship_course.desc": "Reach a course score of 75.",
	"achievement.championship_course.name": "Championship Course",
	"achievement.club_level_five.desc": "Reach club level 5.",
	"achievement.club_level_five.name": "Club Level Five",
	"achievement.club_level_ten.desc": "Reach club level 10.",
	"achievement.club_level_ten.name": "Club Level Ten",
	"achievement.clubhouse_four.desc": "Upgrade the Clubhouse to tier 4.",
	"achievement.clubhouse_four.name": "Clubhouse Four",
	"achievement.clubhouse_three.desc": "Upgrade the Clubhouse to tier 3.",
	"achievement.clubhouse_three.name": "Clubhouse Three",
	"achievement.clubhouse_two.desc": "Upgrade the Clubhouse to tier 2.",
	"achievement.clubhouse_two.name": "Clubhouse Two",
	"achievement.fifty_challenges.desc": "Meet the daily challenge 50 times.",
	"achievement.fifty_challenges.name": "Fifty Challenges",
	"achievement.fifty_members.desc": "Reach 50 members.",
	"achievement.fifty_members.name": "Fifty Members",
	"achievement.fine_course.desc": "Reach a course score of 60.",
	"achievement.fine_course.name": "Fine Course",
	"achievement.fine_dining.desc": "Upgrade the Restaurant to tier 3.",
	"achievement.fine_dining.name": "Fine Dining",
	"achievement.finished_tutorial.desc": "Finish the tutorial.",
	"achievement.finished_tutorial.name": "Finished Tutorial",
	"achievement.first_100k.desc": "Earn $100,000 in total.",
	"achievement.first_100k.name": "First 100k",
	"achievement.first_building.desc": "Buy your first building.",
	"achievement.first_building.name": "First Building",
	"achievement.first_challenge.desc": "Play the daily challenge.",
	"achievement.first_challenge.name": "First Challenge",
	"achievement.first_commission.desc": "Finish your first commission.",
	"achievement.first_commission.name": "First Commission",
	"achievement.first_golfer.desc": "Finish a round with your first golfer.",
	"achievement.first_golfer.name": "First Golfer",
	"achievement.first_hole.desc": "Build your first hole.",
	"achievement.first_hole.name": "First Hole",
	"achievement.first_home.desc": "Upgrade the Homes to tier 1.",
	"achievement.first_home.name": "First Home",
	"achievement.first_million.desc": "Earn $1,000,000 in total.",
	"achievement.first_million.name": "First Million",
	"achievement.first_tournament.desc": "Host your first tournament.",
	"achievement.first_tournament.name": "First Tournament",
	"achievement.five_buildings.desc": "Own 5 buildings.",
	"achievement.five_buildings.name": "Five Buildings",
	"achievement.five_commissions.desc": "Finish 5 commissions.",
	"achievement.five_commissions.name": "Five Commissions",
	"achievement.full_eighteen.desc": "Build 18 holes.",
	"achievement.full_eighteen.name": "Full Eighteen",
	"achievement.full_ladder.desc": "Host a tournament at every level, local to major.",
	"achievement.full_ladder.name": "Full Ladder",
	"achievement.good_hole.desc": "Build a hole that scores 50.",
	"achievement.good_hole.name": "Good Hole",
	"achievement.good_name.desc": "Reach 100 reputation.",
	"achievement.good_name.name": "Good Name",
	"achievement.great_hole.desc": "Build a hole that scores 70.",
	"achievement.great_hole.name": "Great Hole",
	"achievement.great_name.desc": "Reach 500 reputation.",
	"achievement.great_name.name": "Great Name",
	"achievement.guest_rooms.desc": "Upgrade the Lodging to tier 2.",
	"achievement.guest_rooms.name": "Guest Rooms",
	"achievement.keep_trying.desc": "Run two tournaments and pull off at least one.",
	"achievement.keep_trying.name": "Keep Trying",
	"achievement.landmark_built.desc": "Upgrade the Landmark to tier 1.",
	"achievement.landmark_built.name": "Landmark Built",
	"achievement.local_host.desc": "Host a local tournament.",
	"achievement.local_host.name": "Local Host",
	"achievement.major_host.desc": "Host a major tournament.",
	"achievement.major_host.name": "Major Host",
	"achievement.masterpiece_hole.desc": "Build a hole that scores 85.",
	"achievement.masterpiece_hole.name": "Masterpiece Hole",
	"achievement.more_land.desc": "Own 3 parcels of land.",
	"achievement.more_land.name": "More Land",
	"achievement.national_host.desc": "Host a national tournament.",
	"achievement.national_host.name": "National Host",
	"achievement.nine_good_holes.desc": "Have 9 good holes.",
	"achievement.nine_good_holes.name": "Nine Good Holes",
	"achievement.nine_holes.desc": "Build 9 holes.",
	"achievement.nine_holes.name": "Nine Holes",
	"achievement.one_hundred_days.desc": "Play 100 days.",
	"achievement.one_hundred_days.name": "One Hundred Days",
	"achievement.regional_host.desc": "Host a regional tournament.",
	"achievement.regional_host.name": "Regional Host",
	"achievement.regular_visitor.desc": "Play on 14 different days.",
	"achievement.regular_visitor.name": "Regular Visitor",
	"achievement.solid_course.desc": "Reach a course score of 40.",
	"achievement.solid_course.name": "Solid Course",
	"achievement.streak_seven.desc": "Play the daily challenge seven days running.",
	"achievement.streak_seven.name": "Seven Day Streak",
	"achievement.streak_thirty.desc": "Play 30 days in a row.",
	"achievement.streak_thirty.name": "Streak Thirty",
	"achievement.streak_three.desc": "Play 3 days in a row.",
	"achievement.streak_three.name": "Streak Three",
	"achievement.ten_challenges.desc": "Meet the daily challenge 10 times.",
	"achievement.ten_challenges.name": "Ten Challenges",
	"achievement.thirty_days.desc": "Play 30 days.",
	"achievement.thirty_days.name": "Thirty Days",
	"achievement.three_good_holes.desc": "Have 3 good holes.",
	"achievement.three_good_holes.name": "Three Good Holes",
	"achievement.tier_five_first.desc": "Upgrade 1 building to tier 5.",
	"achievement.tier_five_first.name": "Tier Five First",
	"achievement.tier_sum_twenty.desc": "Reach a combined building tier of 20.",
	"achievement.tier_sum_twenty.name": "Tier Sum Twenty",
	"achievement.tournament_veteran.desc": "Host 5 tournaments.",
	"achievement.tournament_veteran.name": "Tournament Veteran",
	"achievement.twenty_commissions.desc": "Finish 20 commissions.",
	"achievement.twenty_commissions.name": "Twenty Commissions",
	"achievement.two_hundred_members.desc": "Reach 200 members.",
	"achievement.two_hundred_members.name": "Two Hundred Members",
	"achievement.varied_clients.desc": "Finish 4 different kinds of commission.",
	"achievement.varied_clients.name": "Varied Clients",
	"advisor.RC001": "No tee placed.",
	"advisor.RC002": "No green placed.",
	"advisor.RC003": "Tee and green are too close or too far apart.",
	"advisor.RC004": "The green is in water or out of bounds.",
	"advisor.RC008": "The tee is in water or out of bounds.",
	"advisor.RC011": "Hole {hole_no} plays very short for its par.",
	"advisor.RC014": "This hole is far too long.",
	"advisor.RC021": "Water or out of bounds leaves golfers no safe line.",
	"advisor.RC023": "Many golfers pick up on this hole.",
	"advisor.RC031": "Dead hole. Golfers skip it.",
	"advisor.RC032": "Weak hole. Add a bend, a hazard or a choice of line.",
	"advisor.RC033": "A strong hole. Golfers will remember it.",
	"advisor.RC039": "Accuracy is rewarded here.",
	"advisor.RC040": "Accuracy barely matters here.",
	"advisor.RC041": "One way to play it. Add a second route.",
	"advisor.RC042": "Two ways to play it.",
	"advisor.RC043": "Three routes make this hole interesting.",
	"advisor.RC047": "A straight line of play. A bend adds choices.",
	"advisor.RC048": "A flat hole. A little height change adds interest.",
	"advisor.RC051": "Not much to look at. Trees, water and rocks help.",
	"advisor.RC064": "Weak holes are dragging the course score down.",
	"advisor.sev.block": "Blocked",
	"advisor.sev.info": "Note",
	"advisor.sev.praise": "Nice",
	"advisor.sev.severe": "Serious",
	"advisor.sev.warn": "Warning",
	"advisor.unknown": "Advisor note {code}",
	"bankrupt.body": "You cannot cover your costs. You are {shortfall} short.",
	"bankrupt.later": "Not now",
	"bankrupt.loan": "Take a bank loan of {amount}",
	"bankrupt.loan_note": "Free, but your reputation drops by {penalty}.",
	"bankrupt.title": "Out of money",
	"bankrupt.tokens": "Recovery plan for {cost} tokens",
	"bankrupt.tokens_note": "You have {have} tokens. Earned tokens are spent first.",
	"bankrupt.tokens_short": "You need {short} more tokens.",
	"build.buy": "Buy tier {tier}",
	"build.cash": "Cash {amount}",
	"build.cost_unknown": "cost set by income",
	"build.demo_note": "Demo: some tiers need the full game",
	"build.details": "Details",
	"build.details_title": "{building}",
	"build.hide_details": "Hide details",
	"build.locked": "Locked",
	"build.maxed": "Fully upgraded",
	"build.more_reasons": "and {count} more",
	"build.need_cash": "Need {amount} more",
	"build.next_cost": "Next: tier {tier} for {cost}",
	"build.next_cost_unknown": "Next: tier {tier}",
	"build.no_catalogue": "The building list could not be loaded.",
	"build.payback": "Pays back in {days} days (+{income} a day, upkeep {upkeep} a day)",
	"build.req.any_others": "Needs {need} other buildings at a higher tier (have {have})",
	"build.req.avg_score": "Needs average hole score {need} (have {have})",
	"build.req.building": "Needs {building} tier {need} (have {have})",
	"build.req.demo": "Not in the demo",
	"build.req.holes": "Needs {need} holes (have {have})",
	"build.req.hosted": "Host a {level} tournament",
	"build.req.members": "Needs {need} members (have {have})",
	"build.req.pace": "Needs pace score {need} (have {have})",
	"build.req.parcel_kind": "Needs a {kind} parcel",
	"build.req.parcels": "Needs {need} parcels (have {have})",
	"build.req.previous": "Needs the previous tier first",
	"build.req.spectators": "Needs room for {need} spectators (have {have})",
	"build.req.staff": "Needs {need} staff (have {have})",
	"build.req.unknown": "Not available yet",
	"build.state.demo": "full game",
	"build.state.locked": "locked",
	"build.state.next": "next",
	"build.state.owned": "owned",
	"build.tier_line": "Tier {tier}: {cost}, payback {days} days ({state})",
	"build.tier_of": "Tier {tier} of {max}",
	"build.title": "Build",
	"build.unlock_full": "Unlock full game",
	"building.cart_barn.desc": "Carts keep rounds moving and pace healthy.",
	"building.cart_barn.name": "Cart barn",
	"building.clubhouse.desc": "Where members gather, check in and book tee times.",
	"building.clubhouse.name": "Clubhouse",
	"building.driving_range.desc": "A practice range that draws more golfers.",
	"building.driving_range.name": "Driving range",
	"building.homes.desc": "Homes beside the course that residents buy into.",
	"building.homes.name": "Homes",
	"building.landmark.desc": "A signature feature that makes the club famous.",
	"building.landmark.name": "Landmark",
	"building.lodging.desc": "Rooms for golfers who stay the night.",
	"building.lodging.name": "Lodging",
	"building.maintenance.desc": "Crews keep the course in good condition.",
	"building.maintenance.name": "Maintenance",
	"building.pool_spa.desc": "Relaxation for members and guests.",
	"building.pool_spa.name": "Pool and spa",
	"building.pro_shop.desc": "Sells clubs and balls and brings in steady income.",
	"building.pro_shop.name": "Pro shop",
	"building.restaurant.desc": "Food and drink for golfers after the round.",
	"building.restaurant.name": "Restaurant",
	"challenge.all_rounder.desc": "Build a par 4 with no weak side: accuracy, imagination, beauty and fairness together.",
	"challenge.all_rounder.title": "All Rounder",
	"challenge.clever_par3.desc": "Build a short par 3 that rewards a clever shot.",
	"challenge.clever_par3.title": "Clever Par 3",
	"challenge.compact_par4.desc": "Build a compact, pretty par 4 that rewards accuracy.",
	"challenge.compact_par4.title": "Compact Par 4",
	"challenge.drivable_par4.desc": "Build a short par 4 that tempts players to go for the green.",
	"challenge.drivable_par4.title": "Drivable Par 4",
	"challenge.fair_play.desc": "Build a hole that treats every golfer fairly.",
	"challenge.fair_play.title": "Fair Play",
	"challenge.gem_par3.desc": "Build a short par 3 that is a joy to look at.",
	"challenge.gem_par3.title": "Gem Par 3",
	"challenge.heroic_par5.desc": "Build a par 5 with a heroic option that tempts a bold player.",
	"challenge.heroic_par5.title": "Heroic Par 5",
	"challenge.length_axis_light.desc": "Build a hole that wins on imagination, not on length.",
	"challenge.length_axis_light.title": "Length Axis Light",
	"challenge.long_haul_par5.desc": "Build a long par 5 that still rewards accuracy.",
	"challenge.long_haul_par5.title": "Long Haul Par 5",
	"challenge.scenic_route.desc": "Build any hole with a beautiful setting that still plays well.",
	"challenge.scenic_route.title": "Scenic Route",
	"challenge.straight_and_true_par4.desc": "Build an honest, fair par 4 that rewards straight hitting.",
	"challenge.straight_and_true_par4.title": "Straight And True Par 4",
	"challenge.strategic_par4.desc": "Build a par 4 that rewards accuracy and offers a choice of line.",
	"challenge.strategic_par4.title": "Strategic par 4",
	"consent.body": "Share anonymous play data so we can fix problems and balance the game. No names, no ads, no typed text. It stays off unless you turn it on.",
	"consent.continue": "Continue",
	"consent.note": "You can change this any time in Settings.",
	"consent.title": "Help improve the game",
	"consent.toggle_off": "Share usage data: Off",
	"consent.toggle_on": "Share usage data: On",
	"daily.attempts": "{left} of {total} attempts left",
	"daily.board": "Leaderboard",
	"daily.board_row": "{rank}. {name}: {score}",
	"daily.completed": "Done for today. You can still improve your best.",
	"daily.ends": "Ends in {time}",
	"daily.paused": "The daily challenge is paused. Check back later.",
	"daily.play": "Play",
	"daily.streak": "Streak: {days} days",
	"daily.target": "Target {score}, your best {best}",
	"daily.title": "Daily challenge",
	"delete.body": "This removes your account and its cloud data. It cannot be undone.",
	"delete.confirm": "Delete account",
	"delete.keep": "Keep account",
	"delete.title": "Delete your account?",
	"editor.done": "Done",
	"editor.radius": "Brush {cells}",
	"editor.redo": "Redo",
	"editor.tool.level": "Level",
	"editor.tool.lower": "Lower",
	"editor.tool.paint": "Paint",
	"editor.tool.raise": "Raise",
	"editor.tool.smooth": "Smooth",
	"editor.undo": "Undo",
	"gallery.back": "Launcher",
	"gallery.cash_low": "Low cash",
	"gallery.cash_rich": "Rich",
	"gallery.demo": "Toggle demo",
	"gallery.left_hand": "Left hand",
	"gallery.recovery_off": "Bankrupt off",
	"gallery.recovery_on": "Bankrupt on",
	"gallery.screen.achievements": "Achievements",
	"gallery.screen.bankruptcy": "Bankruptcy",
	"gallery.screen.build": "Build menu",
	"gallery.screen.confirm_delete": "Delete account",
	"gallery.screen.consent": "Consent",
	"gallery.screen.daily": "Daily challenge",
	"gallery.screen.editor": "Editor toolbar",
	"gallery.screen.hud": "HUD",
	"gallery.screen.land": "Land",
	"gallery.screen.rating": "Hole rating",
	"gallery.screen.score": "Course score",
	"gallery.screen.settings": "Settings",
	"gallery.screen.tokens": "Token store",
	"gallery.screen.tournament": "Tournament",
	"gallery.screen.tutorial_overlay": "Coach overlay",
	"gallery.showing": "Showing: {screen}",
	"gallery.text_down": "Text -",
	"gallery.text_up": "Text +",
	"gallery.title": "UI gallery",
	"gallery.tokens_none": "No tokens",
	"gallery.tokens_some": "10 tokens",
	"gallery.tournament_ready": "Tournament ready",
	"hud.cash": "Cash {amount}",
	"hud.day_time": "Day {day}, {time}",
	"hud.demo": "Demo",
	"hud.nav.build": "Build",
	"hud.nav.editor": "Edit",
	"hud.nav.land": "Land",
	"hud.nav.menu": "Menu",
	"hud.nav.rating": "Rating",
	"hud.net_loss_per_day": "-{amount} a day",
	"hud.net_per_day": "+{amount} a day",
	"hud.pause": "Pause",
	"hud.resume": "Resume",
	"hud.score": "Score {score}",
	"hud.speed.cost": "{rate} token a minute, about {minutes} min left",
	"hud.speed.free": "1x and 2x are free",
	"hud.speed.lock_suffix": "lock",
	"hud.speed.need_tokens": "8x needs tokens",
	"hud.tokens": "Tokens {count}",
	"land.all_owned": "All land owned",
	"land.buy": "Buy for {price}",
	"land.far": "Not next door",
	"land.kind.facility": "Facility",
	"land.kind.golf": "Golf",
	"land.kind.homes": "Homes",
	"land.legend": "Green is yours. You can only buy land next to land you own.",
	"land.need_cash": "Need {amount} more",
	"land.next_price": "Next parcel {price} (you have {cash})",
	"land.owned": "Owned",
	"land.selected": "{kind} parcel for {price}",
	"land.suggested": "Suggested next: {kind}",
	"land.summary": "{owned} of {total} parcels owned. Room for {holes} holes and {homes} homes.",
	"land.title": "Land",
	"land.unavailable": "Land is not available yet",
	"management.title": "Management",
	"management.nav": "Manage",
	"management.unavailable": "Management data unavailable.",
	"management.operations": "Course operations",
	"management.staff_payroll": "Staff {staff}   Payroll {payroll}/day",
	"management.condition_service": "Course condition {condition}/1000   Service {service}/1000",
	"management.course_traffic": "Course traffic: {active} groups playing • {blocked} waiting • Pace support {pace}/100",
	"management.equipment_costs": "Equipment {units}/{capacity}   Operating {operating}   Repairs {repairs}",
	"management.difficulty.relaxed": "Relaxed",
	"management.difficulty.standard": "Standard",
	"management.difficulty.tycoon": "Tycoon",
	"management.attention": "Needs attention",
	"management.warning": "• {warning}",
	"management.staff_number": "#{serial}",
	"management.team": "Team",
	"management.no_staff": "No staff hired yet.",
	"management.employee": "#{serial}  {role}  •  experience {days} days",
	"management.equipment": "Equipment",
	"management.no_equipment": "No equipment owned yet.",
	"management.unit": "#{serial}  {type}  •  {status}{operator}",
	"management.broken": "broken",
	"management.operator": "  •  staff #{serial}",
	"management.hire": "Hire staff",
	"management.hire_row": "{role}   {current}/{cap}   {wage}/day",
	"management.hire_button": "Hire {cost}",
	"management.fleet_shop": "Equipment shop",
	"management.buy_row": "{type}   {price}",
	"management.buy_button": "Buy",
	"management.fire": "Fire",
	"management.assign": "Assign",
	"management.unassign": "Clear",
	"management.sell": "Sell {value}",
	"management.parcel": "Area {parcel}",
	"onboarding.rating": "Nice! Tap Rating to see how golfers score your hole.",
	"onboarding.skip": "Skip",
	"onboarding.stroke": "Drag on the ground to shape your first hole. Two fingers move the camera.",
	"progression.level1.title": "Newcomer",
	"progression.level10.title": "Famous Fairways",
	"progression.level11.title": "Members Pride",
	"progression.level12.title": "Championship Venue",
	"progression.level13.title": "Distinguished Club",
	"progression.level14.title": "National Landmark",
	"progression.level15.title": "Legendary Links",
	"progression.level16.title": "Hall of Fame Course",
	"progression.level17.title": "Icon of the Game",
	"progression.level18.title": "Timeless Club",
	"progression.level19.title": "Wonder of Golf",
	"progression.level2.title": "Weekend Owner",
	"progression.level20.title": "Mulligan Hills Legend",
	"progression.level3.title": "Local Favourite",
	"progression.level4.title": "Rising Club",
	"progression.level5.title": "Respected Course",
	"progression.level6.title": "Regional Name",
	"progression.level7.title": "Destination Course",
	"progression.level8.title": "Established Club",
	"progression.level9.title": "Course of Note",
	"rating.advisor": "Advisor",
	"rating.axis.accuracy": "Accuracy",
	"rating.axis.beauty": "Beauty",
	"rating.axis.imagination": "Imagination",
	"rating.axis.length": "Length",
	"rating.dead": "Dead hole: golfers avoid it",
	"rating.fairness": "Fairness {percent}. An unfair hole cannot be rescued by the other axes.",
	"rating.fewer": "Fewer notes",
	"rating.hole_line": "Hole {hole}, par {par}, {length}",
	"rating.invalid": "This hole cannot be played yet",
	"rating.more": "More notes ({count})",
	"rating.no_holes": "Build a hole to see its rating",
	"rating.no_notes": "No notes for this hole",
	"rating.title": "Hole rating",
	"score.band.fair": "Fair",
	"score.band.good": "Good",
	"score.band.great": "Great",
	"score.band.poor": "Needs work",
	"score.band.superb": "Superb",
	"score.dead": "{count} dead holes (under {line}). They lower the average and do not count toward hole gates.",
	"score.gates_clear": "You are above every score gate",
	"score.hole_n": "Hole {hole}",
	"score.holes_line": "{count} holes, {members} members",
	"score.next_gate": "Tier {tier} buildings need an average hole score of {need}",
	"score.no_holes": "No holes yet",
	"score.open": "Open",
	"score.per_hole": "Holes",
	"score.title": "Course score",
	"score.weakest": "Weakest hole: {hole} (score {score})",
	"settings.access.left_off": "Left-handed layout: Off",
	"settings.access.left_on": "Left-handed layout: On",
	"settings.access.palette": "Colours: {name}",
	"settings.access.text_size": "Text size {percent}%",
	"settings.access.title": "Accessibility",
	"settings.account.delete": "Delete account",
	"settings.account.note": "Restore purchases you made before, or delete your account and its cloud data.",
	"settings.account.replay": "Replay tutorial",
	"settings.account.restore": "Restore purchases",
	"settings.account.title": "Account",
	"settings.fps.30": "30 fps",
	"settings.fps.60": "60 fps",
	"settings.fps.auto": "Auto",
	"settings.fps.note": "30 saves battery. Auto picks by device.",
	"settings.fps.title": "Frame rate",
	"settings.palette.0": "Standard",
	"settings.palette.1": "Deuteranopia",
	"settings.palette.2": "Protanopia",
	"settings.palette.3": "Tritanopia",
	"settings.privacy.note": "Anonymous usage data helps us improve the game. Off by default.",
	"settings.privacy.off": "Usage data: Off",
	"settings.privacy.on": "Usage data: On",
	"settings.privacy.title": "Privacy",
	"settings.title": "Settings",
	"settings.units.imperial": "Imperial",
	"settings.units.metric": "Metric",
	"settings.units.sample": "Example: a {length} hole on a hill {height} high",
	"settings.units.title": "Units",
	"surface.bunker_sand": "Sand",
	"surface.dirt": "Dirt",
	"surface.fairway": "Fairway",
	"surface.first_cut": "First cut",
	"surface.fringe": "Fringe",
	"surface.green": "Green",
	"surface.path": "Path",
	"surface.rough": "Rough",
	"surface.tee": "Tee",
	"surface.waste": "Waste",
	"surface.water": "Water",
	"toast.daily.done": "Challenge complete!",
	"toast.daily.no_attempts": "No attempts left today.",
	"toast.daily.off": "The daily challenge is paused.",
	"toast.daily.tried": "Attempt recorded. {left} left today.",
	"toast.tournament.started": "Tournament started. The course is locked until it ends.",
	"tokens.balance": "{total} tokens",
	"tokens.earn": "Earn tokens by playing: daily visits, challenges, tournaments and achievements.",
	"tokens.never": "Tokens never buy cash or progress.",
	"tokens.pack": "{count} tokens",
	"tokens.pack_price": "Sample price {price}",
	"tokens.placeholder_note": "Token packs are not on sale. This screen is a placeholder.",
	"tokens.split": "{earned} earned, {paid} bought",
	"tokens.title": "Tokens",
	"tokens.unavailable": "Not available yet",
	"tokens.uses": "Tokens speed up time and help you recover from bankruptcy.",
	"tournament.blocked.busy": "Another tournament is already running.",
	"tournament.blocked.cash": "Not enough cash to host.",
	"tournament.blocked.cooldown": "Still cooling down from the last event.",
	"tournament.blocked.disabled": "Tournaments are switched off for now.",
	"tournament.blocked.locked": "The entry checklist is not met.",
	"tournament.blocked.unknown_level": "Unknown tournament level.",
	"tournament.cost_reward": "Cost {cost}. Reward {reward} and {rep} reputation.",
	"tournament.demo_preview": "Demo: tournaments are a preview. Unlock the full game to host one.",
	"tournament.host": "Host",
	"tournament.local.desc": "A friendly one day event for the area. A good first step up the ladder.",
	"tournament.local.name": "Local",
	"tournament.major.desc": "Four days, the strongest field and the biggest stage in the game.",
	"tournament.major.name": "Major",
	"tournament.national.desc": "Three days of play and real crowds. Your course is judged against the best in the country.",
	"tournament.national.name": "National",
	"tournament.regional.desc": "Two days of play with a bigger field from across the region.",
	"tournament.regional.name": "Regional",
	"tournament.status.active": "Running now",
	"tournament.status.available": "Ready to host",
	"tournament.status.cooldown": "Cooling down",
	"tournament.status.locked": "Locked",
	"tournament.title": "Tournaments",
	"ui.common.back": "Back",
	"ui.common.cancel": "Cancel",
	"ui.common.minus": "-",
	"ui.common.ok": "OK",
	"ui.common.plus": "+",
}

static var _logged: Dictionary = {}


static func has_key(key: String) -> bool:
	return TABLE.has(key)


static func key_count() -> int:
	return TABLE.size()


static func keys() -> Array:
	return TABLE.keys()


## Replaces {name} with params["name"]. Unknown placeholders stay as they are. Pure.
static func format(text_value: String, params: Dictionary) -> String:
	var out: String = text_value
	for k: Variant in params.keys():
		out = out.replace("{" + str(k) + "}", str(params[k]))
	return out


static func tr_key(key: String, params: Dictionary = {}) -> String:
	if not TABLE.has(key):
		if not _logged.has(key):
			_logged[key] = true
			push_warning("MHStrings: missing key " + key)
		return "[" + key + "]"
	var resolved: Dictionary = {}
	for k: Variant in params.keys():
		var pname: String = str(k)
		if pname.ends_with("_key"):
			resolved[pname.trim_suffix("_key")] = tr_key(str(params[k]))
		else:
			resolved[pname] = params[k]
	return format(str(TABLE[key]), resolved)


## Short alias used by every screen.
static func t(key: String, params: Dictionary = {}) -> String:
	return tr_key(key, params)

