class_name MHStrings
extends RefCounted
## English string table and lookup. Every visible UI string comes from here by key (docs/spec/data/LOCALIZATION.md:
## keys are permanent, {name} placeholders, no em dashes). A missing key returns "[key]" and logs once; it never crashes.
## Param convention: a param named "x_key" holds a string KEY; it is translated and also offered as {x}.
## The text below is a DRAFT for Nathan to edit (status draft in the localization workflow). The spec file
## game/data/strings/en.json does not exist yet; moving this table there is a follow-up.

const TABLE: Dictionary = {
	"ach.cat.all": "All",
	"ach.cat.buildings": "Buildings",
	"ach.cat.commissions": "Commissions",
	"ach.cat.daily": "Daily",
	"ach.cat.design": "Design",
	"ach.cat.growth": "Growth",
	"ach.cat.misc": "Other",
	"ach.cat.tournaments": "Tournaments",
	"ach.earned": "Earned, {points} points",
	"ach.hidden": "Hidden achievement",
	"ach.progress": "{have} of {need}, {points} points",
	"ach.summary": "{earned} of {total} earned, {points} points",
	"ach.title": "Achievements",
	"achievement.card_player.desc": "Answer an event card.",
	"achievement.card_player.name": "Card Player",
	"achievement.fifty_members.desc": "Reach 50 members.",
	"achievement.fifty_members.name": "Fifty Members",
	"achievement.first_building.desc": "Buy your first building.",
	"achievement.first_building.name": "First Building",
	"achievement.first_challenge.desc": "Play the daily challenge.",
	"achievement.first_challenge.name": "First Challenge",
	"achievement.first_hole.desc": "Build your first hole.",
	"achievement.first_hole.name": "First Hole",
	"achievement.first_tournament.desc": "Host your first tournament.",
	"achievement.first_tournament.name": "First Tournament",
	"achievement.five_buildings.desc": "Own five buildings.",
	"achievement.five_buildings.name": "Five Buildings",
	"achievement.good_hole.desc": "Build a hole that scores 50.",
	"achievement.good_hole.name": "Good Hole",
	"achievement.great_hole.desc": "Build a hole that scores 70.",
	"achievement.great_hole.name": "Great Hole",
	"achievement.more_land.desc": "Buy more land.",
	"achievement.more_land.name": "More Land",
	"achievement.nine_holes.desc": "Build nine holes.",
	"achievement.nine_holes.name": "Nine Holes",
	"achievement.streak_seven.desc": "Play the daily challenge seven days running.",
	"achievement.streak_seven.name": "Seven Day Streak",
	"advisor.RC001": "No tee placed.",
	"advisor.RC002": "No green placed.",
	"advisor.RC003": "Tee and green are too close or too far apart.",
	"advisor.RC004": "The green is in water or out of bounds.",
	"advisor.RC008": "The tee is in water or out of bounds.",
	"advisor.RC011": "Hole {hole_no} plays very short for its par.",
	"advisor.RC014": "This hole is far too long.",
	"advisor.RC021": "Water or out of bounds leaves golfers no safe line.",
	"advisor.RC023": "Many golfers pick up on this hole.",
	"advisor.RC031": "Dead hole. Golfers skip it.",
	"advisor.RC032": "Weak hole. Add a bend, a hazard or a choice of line.",
	"advisor.RC033": "A strong hole. Golfers will remember it.",
	"advisor.RC039": "Accuracy is rewarded here.",
	"advisor.RC040": "Accuracy barely matters here.",
	"advisor.RC041": "One way to play it. Add a second route.",
	"advisor.RC042": "Two ways to play it.",
	"advisor.RC043": "Three routes make this hole interesting.",
	"advisor.RC047": "A straight line of play. A bend adds choices.",
	"advisor.RC048": "A flat hole. A little height change adds interest.",
	"advisor.RC051": "Not much to look at. Trees, water and rocks help.",
	"advisor.RC064": "Weak holes are dragging the course score down.",
	"advisor.sev.block": "Blocked",
	"advisor.sev.info": "Note",
	"advisor.sev.praise": "Nice",
	"advisor.sev.severe": "Serious",
	"advisor.sev.warn": "Warning",
	"advisor.unknown": "Advisor note {code}",
	"bankrupt.body": "You cannot cover your costs. You are {shortfall} short.",
	"bankrupt.later": "Not now",
	"bankrupt.loan": "Take a bank loan of {amount}",
	"bankrupt.loan_note": "Free, but your reputation drops by {penalty}.",
	"bankrupt.title": "Out of money",
	"bankrupt.tokens": "Recovery plan for {cost} tokens",
	"bankrupt.tokens_note": "You have {have} tokens. Earned tokens are spent first.",
	"bankrupt.tokens_short": "You need {short} more tokens.",
	"build.buy": "Buy tier {tier}",
	"build.cash": "Cash {amount}",
	"build.cost_unknown": "cost set by income",
	"build.demo_note": "Demo: some tiers need the full game",
	"build.details": "Details",
	"build.details_title": "{building}",
	"build.hide_details": "Hide details",
	"build.locked": "Locked",
	"build.maxed": "Fully upgraded",
	"build.more_reasons": "and {count} more",
	"build.need_cash": "Need {amount} more",
	"build.next_cost": "Next: tier {tier} for {cost}",
	"build.next_cost_unknown": "Next: tier {tier}",
	"build.no_catalogue": "The building list could not be loaded.",
	"build.payback": "Pays back in {days} days (+{income} a day, upkeep {upkeep} a day)",
	"build.req.any_others": "Needs {need} other buildings at a higher tier (have {have})",
	"build.req.avg_score": "Needs average hole score {need} (have {have})",
	"build.req.building": "Needs {building} tier {need} (have {have})",
	"build.req.demo": "Not in the demo",
	"build.req.holes": "Needs {need} holes (have {have})",
	"build.req.hosted": "Host a {level} tournament",
	"build.req.members": "Needs {need} members (have {have})",
	"build.req.parcel_kind": "Needs a {kind} parcel",
	"build.req.parcels": "Needs {need} parcels (have {have})",
	"build.req.previous": "Needs the previous tier first",
	"build.req.unknown": "Not available yet",
	"build.state.demo": "full game",
	"build.state.locked": "locked",
	"build.state.next": "next",
	"build.state.owned": "owned",
	"build.tier_line": "Tier {tier}: {cost}, payback {days} days ({state})",
	"build.tier_of": "Tier {tier} of {max}",
	"build.title": "Build",
	"build.unlock_full": "Unlock full game",
	"building.cart_barn.desc": "Carts keep rounds moving and pace healthy.",
	"building.cart_barn.name": "Cart barn",
	"building.clubhouse.desc": "Where members gather, check in and book tee times.",
	"building.clubhouse.name": "Clubhouse",
	"building.driving_range.desc": "A practice range that draws more golfers.",
	"building.driving_range.name": "Driving range",
	"building.homes.desc": "Homes beside the course that residents buy into.",
	"building.homes.name": "Homes",
	"building.landmark.desc": "A signature feature that makes the club famous.",
	"building.landmark.name": "Landmark",
	"building.lodging.desc": "Rooms for golfers who stay the night.",
	"building.lodging.name": "Lodging",
	"building.maintenance.desc": "Crews keep the course in good condition.",
	"building.maintenance.name": "Maintenance",
	"building.pool_spa.desc": "Relaxation for members and guests.",
	"building.pool_spa.name": "Pool and spa",
	"building.pro_shop.desc": "Sells clubs and balls and brings in steady income.",
	"building.pro_shop.name": "Pro shop",
	"building.restaurant.desc": "Food and drink for golfers after the round.",
	"building.restaurant.name": "Restaurant",
	"challenge.strategic_par4.desc": "Build a par 4 that rewards accuracy and offers a choice of line.",
	"challenge.strategic_par4.title": "Strategic par 4",
	"consent.body": "Share anonymous play data so we can fix problems and balance the game. No names, no ads, no typed text. It stays off unless you turn it on.",
	"consent.continue": "Continue",
	"consent.note": "You can change this any time in Settings.",
	"consent.title": "Help improve the game",
	"consent.toggle_off": "Share usage data: Off",
	"consent.toggle_on": "Share usage data: On",
	"daily.attempts": "{left} of {total} attempts left",
	"daily.board": "Leaderboard",
	"daily.board_row": "{rank}. {name}: {score}",
	"daily.ends": "Ends in {time}",
	"daily.paused": "The daily challenge is paused. Check back later.",
	"daily.play": "Play",
	"daily.streak": "Streak: {days} days",
	"daily.target": "Target {score}, your best {best}",
	"daily.title": "Daily challenge",
	"delete.body": "This removes your account and its cloud data. It cannot be undone.",
	"delete.confirm": "Delete account",
	"delete.keep": "Keep account",
	"delete.title": "Delete your account?",
	"editor.done": "Done",
	"editor.radius": "Brush {cells}",
	"editor.redo": "Redo",
	"editor.tool.level": "Level",
	"editor.tool.lower": "Lower",
	"editor.tool.paint": "Paint",
	"editor.tool.raise": "Raise",
	"editor.tool.smooth": "Smooth",
	"editor.undo": "Undo",
	"gallery.back": "Launcher",
	"gallery.cash_low": "Low cash",
	"gallery.cash_rich": "Rich",
	"gallery.demo": "Toggle demo",
	"gallery.left_hand": "Left hand",
	"gallery.recovery_off": "Bankrupt off",
	"gallery.recovery_on": "Bankrupt on",
	"gallery.screen.achievements": "Achievements",
	"gallery.screen.bankruptcy": "Bankruptcy",
	"gallery.screen.build": "Build menu",
	"gallery.screen.confirm_delete": "Delete account",
	"gallery.screen.consent": "Consent",
	"gallery.screen.daily": "Daily challenge",
	"gallery.screen.editor": "Editor toolbar",
	"gallery.screen.hud": "HUD",
	"gallery.screen.land": "Land",
	"gallery.screen.rating": "Hole rating",
	"gallery.screen.score": "Course score",
	"gallery.screen.settings": "Settings",
	"gallery.screen.tokens": "Token store",
	"gallery.screen.tournament": "Tournament",
	"gallery.screen.tutorial_overlay": "Coach overlay",
	"gallery.showing": "Showing: {screen}",
	"gallery.text_down": "Text -",
	"gallery.text_up": "Text +",
	"gallery.title": "UI gallery",
	"gallery.tokens_none": "No tokens",
	"gallery.tokens_some": "10 tokens",
	"hud.cash": "Cash {amount}",
	"hud.day_time": "Day {day}, {time}",
	"hud.demo": "Demo",
	"hud.nav.build": "Build",
	"hud.nav.editor": "Edit",
	"hud.nav.land": "Land",
	"hud.nav.menu": "Menu",
	"hud.nav.rating": "Rating",
	"hud.net_loss_per_day": "-{amount} a day",
	"hud.net_per_day": "+{amount} a day",
	"hud.pause": "Pause",
	"hud.resume": "Resume",
	"hud.score": "Score {score}",
	"hud.speed.cost": "{rate} token a minute, about {minutes} min left",
	"hud.speed.free": "1x is free",
	"hud.speed.lock_suffix": "lock",
	"hud.speed.need_tokens": "Speeds above 1x need tokens",
	"hud.tokens": "Tokens {count}",
	"land.all_owned": "All land owned",
	"land.buy": "Buy for {price}",
	"land.far": "Not next door",
	"land.kind.facility": "Facility",
	"land.kind.golf": "Golf",
	"land.kind.homes": "Homes",
	"land.legend": "Green is yours. You can only buy land next to land you own.",
	"land.need_cash": "Need {amount} more",
	"land.next_price": "Next parcel {price} (you have {cash})",
	"land.owned": "Owned",
	"land.selected": "{kind} parcel for {price}",
	"land.suggested": "Suggested next: {kind}",
	"land.summary": "{owned} of {total} parcels owned. Room for {holes} holes and {homes} homes.",
	"land.title": "Land",
	"land.unavailable": "Land is not available yet",
	"onboarding.rating": "Nice! Tap Rating to see how golfers score your hole.",
	"onboarding.skip": "Skip",
	"onboarding.stroke": "Drag on the ground to shape your first hole. Two fingers move the camera.",
	"rating.advisor": "Advisor",
	"rating.axis.accuracy": "Accuracy",
	"rating.axis.beauty": "Beauty",
	"rating.axis.imagination": "Imagination",
	"rating.axis.length": "Length",
	"rating.dead": "Dead hole: golfers avoid it",
	"rating.fairness": "Fairness {percent}. An unfair hole cannot be rescued by the other axes.",
	"rating.fewer": "Fewer notes",
	"rating.hole_line": "Hole {hole}, par {par}, {length}",
	"rating.invalid": "This hole cannot be played yet",
	"rating.more": "More notes ({count})",
	"rating.no_holes": "Build a hole to see its rating",
	"rating.no_notes": "No notes for this hole",
	"rating.title": "Hole rating",
	"score.band.fair": "Fair",
	"score.band.good": "Good",
	"score.band.great": "Great",
	"score.band.poor": "Needs work",
	"score.band.superb": "Superb",
	"score.dead": "{count} dead holes (under {line}). They lower the average and do not count toward hole gates.",
	"score.gates_clear": "You are above every score gate",
	"score.hole_n": "Hole {hole}",
	"score.holes_line": "{count} holes, {members} members",
	"score.next_gate": "Tier {tier} buildings need an average hole score of {need}",
	"score.no_holes": "No holes yet",
	"score.open": "Open",
	"score.per_hole": "Holes",
	"score.title": "Course score",
	"score.weakest": "Weakest hole: {hole} (score {score})",
	"settings.access.left_off": "Left-handed layout: Off",
	"settings.access.left_on": "Left-handed layout: On",
	"settings.access.palette": "Colours: {name}",
	"settings.access.text_size": "Text size {percent}%",
	"settings.access.title": "Accessibility",
	"settings.account.delete": "Delete account",
	"settings.account.note": "Restore purchases you made before, or delete your account and its cloud data.",
	"settings.account.replay": "Replay tutorial",
	"settings.account.restore": "Restore purchases",
	"settings.account.title": "Account",
	"settings.fps.30": "30 fps",
	"settings.fps.60": "60 fps",
	"settings.fps.auto": "Auto",
	"settings.fps.note": "30 saves battery. Auto picks by device.",
	"settings.fps.title": "Frame rate",
	"settings.palette.0": "Standard",
	"settings.palette.1": "Deuteranopia",
	"settings.palette.2": "Protanopia",
	"settings.palette.3": "Tritanopia",
	"settings.privacy.note": "Anonymous usage data helps us improve the game. Off by default.",
	"settings.privacy.off": "Usage data: Off",
	"settings.privacy.on": "Usage data: On",
	"settings.privacy.title": "Privacy",
	"settings.title": "Settings",
	"settings.units.imperial": "Imperial",
	"settings.units.metric": "Metric",
	"settings.units.sample": "Example: a {length} hole on a hill {height} high",
	"settings.units.title": "Units",
	"surface.bunker_sand": "Sand",
	"surface.dirt": "Dirt",
	"surface.fairway": "Fairway",
	"surface.first_cut": "First cut",
	"surface.fringe": "Fringe",
	"surface.green": "Green",
	"surface.path": "Path",
	"surface.rough": "Rough",
	"surface.tee": "Tee",
	"surface.waste": "Waste",
	"surface.water": "Water",
	"tokens.balance": "{total} tokens",
	"tokens.earn": "Earn tokens by playing: daily visits, challenges, tournaments and achievements.",
	"tokens.never": "Tokens never buy cash or progress.",
	"tokens.pack": "{count} tokens",
	"tokens.pack_price": "Sample price {price}",
	"tokens.placeholder_note": "Token packs are not on sale. This screen is a placeholder.",
	"tokens.split": "{earned} earned, {paid} bought",
	"tokens.title": "Tokens",
	"tokens.unavailable": "Not available yet",
	"tokens.uses": "Tokens speed up time and help you recover from bankruptcy.",
	"tournament.cost_reward": "Cost {cost}. Reward {reward} and {rep} reputation.",
	"tournament.demo_preview": "Demo: tournaments are a preview. Unlock the full game to host one.",
	"tournament.host": "Host",
	"tournament.local.name": "Local",
	"tournament.major.name": "Major",
	"tournament.national.name": "National",
	"tournament.regional.name": "Regional",
	"tournament.status.active": "Running now",
	"tournament.status.available": "Ready to host",
	"tournament.status.cooldown": "Cooling down",
	"tournament.status.locked": "Locked",
	"tournament.title": "Tournaments",
	"ui.common.back": "Back",
	"ui.common.cancel": "Cancel",
	"ui.common.minus": "-",
	"ui.common.ok": "OK",
	"ui.common.plus": "+",
}

static var _logged: Dictionary = {}


static func has_key(key: String) -> bool:
	return TABLE.has(key)


static func key_count() -> int:
	return TABLE.size()


static func keys() -> Array:
	return TABLE.keys()


## Replaces {name} with params["name"]. Unknown placeholders stay as they are. Pure.
static func format(text_value: String, params: Dictionary) -> String:
	var out: String = text_value
	for k: Variant in params.keys():
		out = out.replace("{" + str(k) + "}", str(params[k]))
	return out


static func tr_key(key: String, params: Dictionary = {}) -> String:
	if not TABLE.has(key):
		if not _logged.has(key):
			_logged[key] = true
			push_warning("MHStrings: missing key " + key)
		return "[" + key + "]"
	var resolved: Dictionary = {}
	for k: Variant in params.keys():
		var pname: String = str(k)
		if pname.ends_with("_key"):
			resolved[pname.trim_suffix("_key")] = tr_key(str(params[k]))
		else:
			resolved[pname] = params[k]
	return format(str(TABLE[key]), resolved)


## Short alias used by every screen.
static func t(key: String, params: Dictionary = {}) -> String:
	return tr_key(key, params)

