extends GdUnitTestSuite
## Golden-vector tests for MHEntitlementToken. Vectors generated by
## supabase/functions/verify-purchase/make_golden.py (Python `cryptography`, RSA-2048 TEST key).
## NOT YET RUN (Godot cannot run in the authoring sandbox). Verifies that Godot's mbedTLS-backed
## Crypto.verify accepts a PKCS#1 v1.5 SHA-256 signature made by Python/WebCrypto: the single biggest unknown here.

const FIX: String = "res://platform/tests/fixtures/"

func _golden() -> Dictionary:
	return JSON.parse_string(FileAccess.get_file_as_string(FIX + "golden.json")) as Dictionary

func _pub() -> String:
	return FileAccess.get_file_as_string(FIX + "test_public.pem")

func test_valid_token_verifies() -> void:
	var g: Dictionary = _golden()
	var r: Dictionary = MHEntitlementToken.verify(str(g["valid"]), _pub(), "com.mulliganhills.game", "mh_full_unlock")
	assert_bool(bool(r["ok"])).is_true()
	assert_str(str((r["payload"] as Dictionary)["pid"])).is_equal("mh_full_unlock")

func test_tampered_payload_rejected() -> void:
	var g: Dictionary = _golden()
	var r: Dictionary = MHEntitlementToken.verify(str(g["tampered"]), _pub(), "com.mulliganhills.game", "other_product")
	assert_bool(bool(r["ok"])).is_false()
	assert_str(str(r["reason"])).is_equal("bad_signature")

func test_wrong_package_rejected() -> void:
	var g: Dictionary = _golden()
	var r: Dictionary = MHEntitlementToken.verify(str(g["valid"]), _pub(), "com.other.app", "mh_full_unlock")
	assert_str(str(r["reason"])).is_equal("wrong_package")

func test_wrong_product_rejected() -> void:
	var g: Dictionary = _golden()
	var r: Dictionary = MHEntitlementToken.verify(str(g["valid"]), _pub(), "com.mulliganhills.game", "nope")
	assert_str(str(r["reason"])).is_equal("wrong_product")

func test_garbage_rejected() -> void:
	var r: Dictionary = MHEntitlementToken.verify("abc", _pub(), "x", "y")
	assert_str(str(r["reason"])).is_equal("malformed")

func test_empty_key_rejected() -> void:
	var g: Dictionary = _golden()
	var r: Dictionary = MHEntitlementToken.verify(str(g["valid"]), "", "com.mulliganhills.game", "mh_full_unlock")
	assert_str(str(r["reason"])).is_equal("no_public_key")

func test_needs_refresh() -> void:
	assert_bool(MHEntitlementToken.needs_refresh({"ref": 100}, 99)).is_false()
	assert_bool(MHEntitlementToken.needs_refresh({"ref": 100}, 100)).is_true()

func test_request_hash_vector() -> void:
	var h: String = MHIntegrityService.request_hash(PackedStringArray(["a", "b", "c"]))
	assert_str(h).is_equal("a52dd81bfd5e4e66d96b9f598382f6cbf8c5c3897654e6ae9055e03620fcf38e")
