class_name MHTrig
extends RefCounted
## Integer trig via lookup tables (mh_trig_table.gd, generated by tools/reference/determinism/gen_tables.py).
## Angles are "brads16": 65536 units = one full turn (0 = +x, counter-clockwise). Any int is accepted
## (masked with & 0xFFFF, which is well defined for negatives in two's complement).
## sin/cos return Q16.16 in [-65536, 65536].
## Max error (measured in the Python reference against float math, 65536 angles): sin/cos 1.70 LSB
## (1.70/65536 = 2.6e-5); atan2 1.57 brads (0.0086 degrees). Documented bound: 2 LSB / 2 brads.


static func _qs(r: int) -> int:
	# r in 0..16384, table step 64 units, linear interpolation. Table is monotonic so the diff is >= 0.
	var idx: int = r >> 6
	if idx >= 256:
		return MHTrigTable.SIN_QUARTER[256]
	var frac: int = r & 63
	var a: int = MHTrigTable.SIN_QUARTER[idx]
	var b: int = MHTrigTable.SIN_QUARTER[idx + 1]
	return a + (((b - a) * frac) >> 6)


static func sin_brad(angle: int) -> int:
	var a: int = angle & 0xFFFF
	var q: int = a >> 14
	var r: int = a & 16383
	if q == 0:
		return _qs(r)
	if q == 1:
		return _qs(16384 - r)
	if q == 2:
		return -_qs(r)
	return -_qs(16384 - r)


static func cos_brad(angle: int) -> int:
	return sin_brad(angle + 16384)


static func _atan_q(r: int) -> int:
	# r = ratio in Q16.16, 0..65536 -> brads 0..8192
	var idx: int = r >> 8
	if idx >= 256:
		return MHTrigTable.ATAN_OCTANT[256]
	var frac: int = r & 255
	var a: int = MHTrigTable.ATAN_OCTANT[idx]
	var b: int = MHTrigTable.ATAN_OCTANT[idx + 1]
	return a + (((b - a) * frac) >> 8)


## Angle of vector (x, y) in brads16, 0..65535. atan2_brad(0, 0) = 0. |x|,|y| < 2^46.
@warning_ignore("integer_division")
static func atan2_brad(y: int, x: int) -> int:
	var ax: int = absi(x)
	var ay: int = absi(y)
	if ax == 0 and ay == 0:
		return 0
	var base: int
	if ay <= ax:
		base = _atan_q((ay * 65536) / ax)
	else:
		base = 16384 - _atan_q((ax * 65536) / ay)
	if x >= 0:
		if y >= 0:
			return base
		return (65536 - base) & 0xFFFF
	if y >= 0:
		return 32768 - base
	return 32768 + base
